# -*- coding: utf-8 -*-
"""Another copy of omni_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJCBf8smt94k32NprShNg2UlUTC7Gc40
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import datetime as dt
import datetime
from datetime import datetime

!pip install pymsis

!pip install pyamps

!unzip /content/drive/MyDrive/warmup.zip
!unzip /content/drive/MyDrive/Sat_Density.zip



dfchamp1=pd.read_csv("/content/drive/MyDrive/champ_-00029-20001019_to_20001022.csv",skiprows=0)
dfchamp2=pd.read_csv("/content/drive/MyDrive/champ_-00029-20001019_to_20001022.csv",skiprows=0)
dfgoes1=pd.read_csv("/content/drive/MyDrive/goes-00017-20000727_to_20000925.csv",skiprows=0)
dfgoes2=pd.read_csv("/content/drive/MyDrive/goes-00037-20000901_to_20001031.csv",skiprows=0)

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler


def prep_data(df1, df2):
    """
    Prepares the combined dataset by merging, handling missing values, and normalizing.

    Parameters:
        df1 (pd.DataFrame): The first dataset with 'Orbit Mean Density (kg/m^3)'.
        df2 (pd.DataFrame): The second dataset with X-ray flux measurements.

    Returns:
        pd.DataFrame: The combined and preprocessed DataFrame.
    """
    # Ensure the index is datetime (if not already)
    df1.index = pd.to_datetime(df1.index)
    df2.index = pd.to_datetime(df2.index)

    # Resample to align timestamps (assuming 1-minute interval as an example)
    df1 = df1.resample('1T').mean()
    df2 = df2.resample('1T').mean()

    # Merge datasets by index
    combined_df = pd.merge(df1, df2, left_index=True, right_index=True, how='outer')

    # Sort by index (timestamp)
    combined_df = combined_df.sort_index().reset_index()
    print("combined_df head",combined_df.head())
    # Handle missing values
    combined_df["Orbit Mean Density (kg/m^3)"] = combined_df['Orbit Mean Density (kg/m^3)'] \
        .interpolate(method='linear').fillna(method='bfill').fillna(method='ffill')

    combined_df = combined_df.fillna(method='ffill').interpolate(method='linear').fillna(method='bfill')

    # Normalize numerical columns except the target variable
    numerical_columns = ['xrsa_flux', 'xrsb_flux', 'xrsa_flux_observed', 'xrsb_flux_observed']
    scaler = MinMaxScaler()
    combined_df[numerical_columns] = scaler.fit_transform(combined_df[numerical_columns])

    return combined_df



def prep_data2(df1, df2):
    """
    Prepares the combined dataset by merging, handling missing values, and normalizing.

    Parameters:
        df1 (pd.DataFrame): The first dataset with 'Orbit Mean Density (kg/m^3)'.
        df2 (pd.DataFrame): The second dataset with X-ray flux measurements.

    Returns:
        pd.DataFrame: The combined and preprocessed DataFrame.
    """
    # Ensure the index is datetime (if not already)
    df1.index = pd.to_datetime(df1.index)
    df2.index = pd.to_datetime(df2.index)

    # Resample to align timestamps (assuming 1-minute interval as an example)
    df1 = df1.resample('1T').mean()
    df2 = df2.resample('1T').mean()

    # Merge datasets by index
    combined_df = pd.merge(df1, df2, left_index=True, right_index=True, how='outer')

    # Sort by index (timestamp)
    combined_df = combined_df.sort_index().reset_index()

    # Handle missing values
    combined_df["Orbit Mean Density (kg/m^3)"] = combined_df['Orbit Mean Density (kg/m^3)'] \
        .interpolate(method='linear').fillna(method='bfill').fillna(method='ffill')

    combined_df = combined_df.fillna(method='ffill').interpolate(method='linear').fillna(method='bfill')

    # Normalize numerical columns except the target variable
    numerical_columns = combined_df.columns.remove("'Orbit Mean Density (kg/m^3)'")
    scaler = MinMaxScaler()
    combined_df[numerical_columns] = scaler.fit_transform(combined_df[numerical_columns])

    return combined_df

dfchamp1.head()
dfchamp1.tail()

dfchamp2.head()
dfchamp2.tail()

dfgoes1.head()
dfgoes1.tail()

def fix_time(df1,df2):
  df1['Timestamp'] = pd.to_datetime(df1['Timestamp'])

  df1.set_index('Timestamp', inplace=True)

  df2['Timestamp'] = pd.to_datetime(df2['Timestamp'])

  df2.set_index('Timestamp', inplace=True)

  combined_index = df1.index.union(df2.index)  # Union of both indices
  df1 = df1.reindex(combined_index)
  df2 = df2.reindex(combined_index)

  # Interpolate missing values
  df1.interpolate(method='time', inplace=True)
  df2.interpolate(method='time', inplace=True)

  # Combine the two DataFrames
  merged_df = pd.concat([df1, df2], axis=0)

  # Interpolate missing values in the merged DataFrame
  merged_df.interpolate(method='time', inplace=True)

  return merged_df

import pandas as pd
import numpy as np

def fill_nan_with_mean(df):
    """
    Fills NaN values in each column of a DataFrame with the mean of that column.

    Parameters:
        df (pd.DataFrame): The input DataFrame.

    Returns:
        pd.DataFrame: The DataFrame with NaN values filled.
    """
    # Loop through each column
    for column in df.columns:
        # Calculate the mean of the column (ignoring NaN values)
        column_mean = df[column].mean()

        # Fill NaN values with the mean
        df[column].fillna(column_mean, inplace=True)

    return df



merged_c=fix_time(dfchamp1,dfchamp2)
merged_g=fix_time(dfgoes1,dfgoes2)

merged_c.head()

merged_c.isna().sum()

merged_c.tail()



merged_g.head()

merged_g.columns



dfgoes2.index

dfchamp2.index

#combined_goes = pd.concat([dfgoes1,dfgoes2] , join='outer' ,axis=1)
#df_o.index = pd.to_datetime(df_o.index)
#combined_champ = pd.concat([dfchamp1,dfchamp2] , join='outer' ,axis=1)
combined_all=prep_data(merged_c,merged_g)
#combined_all=pd.concat([merged_g,merged_c] ,join='outer'  )

combined_all

combined_all.isna().sum()

combined_all.columns

len(combined_all)

combined_all_drop=combined_all[["xrsa_flux","xrsb_flux","xrsa_flag","xrsb_flag",'Orbit Mean Density (kg/m^3)']]

combined_all_dropjoin='outer'

combined_all_filled = fill_nan_with_mean(combined_all_drop)

combined_all_filled.isna().sum()

combined_all_filled.corr()

combined_all_filled.head()

combined_all_filled.index=combined_all.index

data = pd.read_csv("/content/SWARMA_POD_RD_01282014-01272020.csv", skiprows=0)
data2=pd.read_csv("/content/swarma-wu339-20161107_to_20161110.csv", skiprows=0)
data3=pd.read_csv("/content/swarma-wu002-20140131_to_20140203.csv",skiprows=0)



print(data2.head())

#print(data.head())
print(data.tail())

combined_data=fix_time(data2,data3)

combined_data

combined_data.index

combined_data.isna().sum()

combined_all_plus_data=prep_data2(combined_data,data)

combined_all_filled

!pip install filterpy

import pandas
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import MinMaxScaler
"""
def prep_2020(df_2020,df_2014_2020):
  df_2020_resampled = df_2020.resample('H').mean()  # Example: Resample to hourly frequency
  combined_df = pd.merge(df_2014_2020, df_2020_resampled, on='Timestamp', how='outer')

  combined_df = combined_df.sort_values(by='Timestamp')

  combined_df = combined_df.reset_index(drop=True)
  combined_df = combined_df.fillna(method='ffill')

  combined_df = combined_df.interpolate(method='linear')


  numerical_columns = [
    'value1', 'value2', 'inclination (deg)', 'raan (deg)', 'arg_perigee (deg)', 'true_anomaly (deg)',
    'xrsa_flux', 'xrsb_flux']

  scaler = MinMaxScaler()

  combined_df[numerical_columns] = scaler.fit_transform(combined_df[numerical_columns])
  return combined_df

  """


def prep_2020(df_2020, df_2014_2020):
    """
    Prepares the 2020 dataset and merges it with the 2014–2020 dataset.

    Parameters:
        df_2020 (pd.DataFrame): The 2020 dataset with 'Timestamp' as the index.
        df_2014_2020 (pd.DataFrame): The 2014–2020 dataset with a 'Timestamp' column.

    Returns:
        pd.DataFrame: The combined and preprocessed DataFrame.
    """
    # Convert 'Timestamp' column to datetime in both DataFrames
    df_2014_2020.index = pd.to_datetime(df_2014_2020.index)
    df_2020.index = pd.to_datetime(df_2020.index)

    # Resample the 2020 dataset to hourly frequency
    df_2020_resampled = df_2020.resample('h').mean()  # Use 'h' instead of 'H'

    # Reset index if 'Timestamp' is the index in one DataFrame
    df_2020_reset = df_2020_resampled.reset_index()

    # Merge datasets on Timestamp
    combined_df = pd.merge(df_2014_2020, df_2020_reset, on='Timestamp', how='outer')

    # Sort by timestamp
    combined_df = combined_df.sort_values(by='Timestamp')

    # Reset index
    combined_df = combined_df.reset_index(drop=True)

    # Handle missing values
    combined_df = combined_df.fillna(method='ffill')
    combined_df = combined_df.interpolate(method='linear')

    # Normalize numerical columns
    numerical_columns = [
       'inclination (deg)', 'raan (deg)', 'arg_perigee (deg)', 'true_anomaly (deg)',
        'xrsa_flux', 'xrsb_flux'
    ]
    scaler = MinMaxScaler()
    combined_df[numerical_columns] = scaler.fit_transform(combined_df[numerical_columns])

    return combined_df

"""

def get_train_test(combined_df):

  numerical_columns = [
    'value1', 'value2', 'inclination (deg)', 'raan (deg)', 'arg_perigee (deg)', 'true_anomaly (deg)',
    'xrsa_flux', 'xrsb_flux']
  sequence_length = 24

  X, y = [], []
  for i in range(len(combined_df) - sequence_length):
    X.append(combined_df[numerical_columns].iloc[i:i+sequence_length].values)
    y.append(combined_df[numerical_columns].iloc[i+sequence_length].values)

  X = np.array(X)
  y = np.array(y)
  train_size = int(len(X) * 0.8)
  X_train, X_test = X[:train_size], X[train_size:]
  y_train, y_test = y[:train_size], y[train_size:]
  return X_train,y_train


  """

def get_train_test(combined_df):
    """
    Creates sequences and splits the data into training and testing sets.

    Parameters:
        combined_df (pd.DataFrame): The combined and preprocessed DataFrame.

    Returns:
        tuple: (X_train, y_train, X_test, y_test)
    """
    numerical_columns = [
        'inclination (deg)', 'raan (deg)', 'arg_perigee (deg)', 'true_anomaly (deg)',
        'xrsa_flux', 'xrsb_flux'
    ]
    sequence_length = 24

    # Create sequences
    X, y = [], []
    for i in range(len(combined_df) - sequence_length):
        X.append(combined_df[numerical_columns].iloc[i:i+sequence_length].values)
        y.append(combined_df[numerical_columns].iloc[i+sequence_length].values)

    # Convert to numpy arrays
    X = np.array(X)
    y = np.array(y)

    # Train-test split
    train_size = int(len(X) * 0.8)
    X_train, X_test = X[:train_size], X[train_size:]
    y_train, y_test = y[:train_size], y[train_size:]

    return X_train, y_train, X_test, y_test

df_2020=combined_all_filled
df_2014_2020=data

combined_df=prep_2020(df_2020,df_2014_2020)
X_train,y_train, X_test, y_test=get_train_test(combined_df)

X_train

df_2014_2020

import numpy as np
import pandas as pd
from filterpy.kalman import ExtendedKalmanFilter

# Define the EKF application function
def apply_ekf(df, state_transition_function, observation_function, jacobian_state_transition, jacobian_observation, process_noise=0.01, observation_noise=0.1):
    """
    Applies the Extended Kalman Filter (EKF) to a DataFrame with a 'Value' column.

    Parameters:
        df (pd.DataFrame): Input DataFrame with a 'Value' column and a 'Timestamp' index.
        state_transition_function (callable): Non-linear state transition function.
        observation_function (callable): Non-linear observation function.
        jacobian_state_transition (callable): Jacobian of the state transition function.
        jacobian_observation (callable): Jacobian of the observation function.
        process_noise (float): Process noise covariance.
        observation_noise (float): Observation noise covariance.

    Returns:
        pd.DataFrame: DataFrame with an additional 'Smoothed_Value' column containing the EKF estimates.
    """
    # Initialize EKF
    ekf = ExtendedKalmanFilter(dim_x=1, dim_z=1)
    ekf.x = np.array([df['Value'].mean()])  # Initial state estimate
    ekf.P = np.array([1])  # Initial error covariance
    ekf.Q = np.array([process_noise])  # Process noise covariance
    ekf.R = np.array([observation_noise])  # Observation noise covariance
    ekf.F = jacobian_state_transition  # State transition Jacobian
    ekf.H = jacobian_observation  # Observation Jacobian

    # Apply EKF
    smoothed_values = []
    for z in df['Value'].values:
        if np.isnan(z):
            # Predict step only if observation is missing
            ekf.predict()
        else:
            # Predict and update steps
            ekf.predict()
            ekf.update(np.array([z]), HJacobian=jacobian_observation, Hx=observation_function)
        smoothed_values.append(ekf.x[0])

    # Add smoothed values to DataFrame
    df['Smoothed_Value'] = smoothed_values
    return df

# Example: Simulated non-linear sensor data (sine wave with noise)
timestamps_2013_2018 = pd.date_range(start='2013-01-01', end='2018-12-31', freq='H')
values_2013_2018 = np.sin(np.arange(len(timestamps_2013_2018)) * 0.1) + np.random.normal(0, 0.1, len(timestamps_2013_2018))
values_2013_2018[np.random.choice(len(values_2013_2018), size=1000, replace=False)] = np.nan  # Introduce missing values

timestamps_2020 = pd.date_range(start='2020-01-01', end='2020-12-31', freq='H')
values_2020 = np.sin(np.arange(len(timestamps_2020)) * 0.1) + np.random.normal(0, 0.1, len(timestamps_2020))
values_2020[np.random.choice(len(values_2020), size=500, replace=False)] = np.nan  # Introduce missing values

# Create DataFrames
df_2013_2018 = pd.DataFrame({'Timestamp': timestamps_2013_2018, 'Value': values_2013_2018})
df_2020 = pd.DataFrame({'Timestamp': timestamps_2020, 'Value': values_2020})
df_2013_2018.set_index('Timestamp', inplace=True)
df_2020.set_index('Timestamp', inplace=True)

# Define non-linear functions and Jacobians
def state_transition_function(x, dt):
    """Non-linear state transition function."""
    return x + np.sin(x) * dt  # Example: Non-linear dynamics

def observation_function(x):
    """Non-linear observation function."""
    return np.sin(x)  # Example: Non-linear observation

def jacobian_state_transition(x, dt):
    """Jacobian of the state transition function."""
    return 1 + np.cos(x) * dt  # Derivative of state_transition_function

def jacobian_observation(x):
    """Jacobian of the observation function."""
    return np.cos(x)  # Derivative of observation_function

# Apply EKF to both datasets
df_2013_2018 = apply_ekf(
    data,
    state_transition_function,
    observation_function,
    jacobian_state_transition,
    jacobian_observation
)

df_2020 = apply_ekf(
    combined_all_filled,
    state_transition_function,
    observation_function,
    jacobian_state_transition,
    jacobian_observation
)

# Combine datasets
combined_df = pd.concat([df_2013_2018, df_2020], axis=0)
combined_df = combined_df.sort_values(by='Timestamp')

# Display the result
print(combined_df.head())

filtered_df_a.head()

df_wu = pd.read_csv("/content/swarma-wu704-20191110_to_20191113.csv", skiprows=0)

df_wu.head()

df_wu.tail()

#df_wu["Formatted_Timestamp"]  = pd.to_datetime(df_wu["Timestamp"]).dt.date

#df_wu["Formatted_Timestamp"].head()
#df_wu.drop("Timestamp",axis=1,inplace=True)

df_wu.set_index("Timestamp", inplace=True)

df_wu_i=df_wu.copy()
df_wu_i.index = pd.to_datetime(df_wu.index)

df_wu_i.head()

start_date = "2018-11-26"
end_date = "2020-01-24"
filtered_df_wu = df_wu_i.loc[start_date:end_date]
print(filtered_df_wu)


common_dates = filtered_df_wu.index.intersection(filtered_df_wu.index)
filtered_df_wu = filtered_df_wu.loc[common_dates]

combined_all = pd.merge(filtered_df_wu, filtered_df_a, left_index=True, right_index=True)
#combined_all['Year'] = combined_all['Formatted_Timestamp'].dt.year
#combined_all['Month'] = combined_all['Formatted_Timestamp'].dt.month
#combined_all['Day'] = combined_all['Formatted_Timestamp'].dt.day

combined_all.head()

combined_all.columns



from sklearn.preprocessing import StandardScaler

# Example: Scaling selected features
features_to_scale = [
    "semi_major_axis (km)", "eccentricity (km) ", "inclination (deg)"
]
scaler = StandardScaler()
combined_all[features_to_scale] = scaler.fit_transform(combined_all[features_to_scale])

print(combined_all.isnull().sum())  # Check for missing values
print(combined_all.describe())

combined_all = combined_all.replace([np.inf, -np.inf], np.nan)
combined_all = combined_all.dropna(how="all")
combined_all.loc[(combined_all!=0).any(axis=1)]

combined_all.head()

print("Missing Values:\n", combined_all.isnull().sum())

combined_all.corr()

combined_all.describe()

combined_all = combined_all.loc[:, combined_all.var() != 0]

combined_all.corr()



correlation_matrix = combined_all.corr()

nan_columns = correlation_matrix.columns[correlation_matrix.isna().any()]
nan_rows = correlation_matrix.index[correlation_matrix.isna().any(axis=1)]

# Step 3: Drop columns and rows with NaN correlations
df_cleaned = combined_all.drop(columns=nan_columns)  # Drop columns with NaN correlation
df_cleaned = df_cleaned.dropna()

nan_columns

combined_all.drop(["Proton_flux_>4_Mev","Proton_flux_>2_Mev","Proton_flux_>1_Mev"],axis=1,inplace=True)

combined_all.corr()

target_column = "Orbit Mean Density (kg/m^3)"
combined_all_c=combined_all.copy()
combined_all_x=combined_all_c.drop(target_column, axis=1)
combined_all_y=combined_all_c[target_column]



print("Dataset Shape:", combined_all.shape)
print("Columns:", combined_all.columns)

# Check for missing values
print("Missing Values:\n", combined_all.isnull().sum())

# Ensure the target column is present
assert target_column in combined_all.columns, f"{target_column} not found in dataset!"

seq=25
X, y = [], []
for i in range(len(combined_all_c) - seq):
    X.append(combined_all_x.iloc[i:i + seq].values)
    y.append(combined_all_y.iloc[i + seq])
X, y = np.array(X), np.array(y)
print(X.shape,y.shape)

def prep_data(df,se_len):
  X, y = [], []
  target_column = "Orbit Mean Density (kg/m^3)"

  for i in range(len(combined_all) - se_len):
    X.append(combined_all.iloc[i:i + se_len].drop(target_column, axis=1).values)
    y.append(combined_all.iloc[i + se_len][target_column])
    X, y = np.array(X), np.array(y)
    return X,y

from statsmodels.tsa.stattools import acf, pacf

# Calculate ACF and PACF
acf_values = acf(combined_all_y, nlags=30)
pacf_values = pacf(combined_all_y, nlags=30, method="ywm")

print("ACF Values:", acf_values)
print("PACF Values:", pacf_values)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
plt.figure(figsize=(12, 6))

# Autocorrelation Function
plt.subplot(2, 1, 1)
plot_acf(combined_all_y, lags=30, ax=plt.gca())
plt.title("Autocorrelation Function (ACF)")

# Partial Autocorrelation Function
plt.subplot(2, 1, 2)
plot_pacf(combined_all_y, lags=30, ax=plt.gca(), method="ywm")
plt.title("Partial Autocorrelation Function (PACF)")

plt.tight_layout()
plt.show()

def initialize_weights(model):
    for layer in model.modules():
        if isinstance(layer, nn.Linear):
            nn.init.xavier_uniform_(layer.weight)
            if layer.bias is not None:
                nn.init.zeros_(layer.bias)

class TemporalSpatialTransformer(nn.Module):
    def __init__(self, input_dim, sequence_length, num_heads, num_layers, hidden_dim):
        super().__init__()
        self.embedding = nn.Linear(input_dim, hidden_dim)  # Project input_dim to hidden_dim
        self.transformer = nn.Transformer(
            d_model=hidden_dim,
            nhead=num_heads,
            num_encoder_layers=num_layers,
            num_decoder_layers=num_layers,
            dim_feedforward=hidden_dim * 4,
            batch_first=True,
        )
        self.fc = nn.Linear(hidden_dim, 1)  # Final layer to predict a single value

    def forward(self, x):
        # x shape: (batch_size, sequence_length, input_dim)
        x = self.embedding(x)  # Shape: (batch_size, sequence_length, hidden_dim)
        x = self.transformer(x, x)  # Shape: (batch_size, sequence_length, hidden_dim)
        x = x.mean(dim=1)  # Pool across the sequence dimension
        return self.fc(x)  # Shape: (batch_size, 1)


model = TemporalSpatialTransformer(
    input_dim=18,           # Matches the feature dimension
    sequence_length=25,     # Matches the sequence length
    num_heads=4,            # Ensure `embed_dim` is divisible by `num_heads`
    num_layers=2,
    hidden_dim=128          # Embed dimension, ensure it's divisible by `num_heads`
)

from torch.utils.data import DataLoader, TensorDataset
from torch.optim import Adam


# Convert data to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.float32).unsqueeze(1)

dataset = TensorDataset(X_tensor, y_tensor)

dataloader = DataLoader(dataset, batch_size=64, shuffle=True)

# Initialize model, loss, and optimizer
criterion = nn.MSELoss()
optimizer = Adam(model.parameters(), lr=0.001)

# Training loop
for epoch in range(50):  # Adjust epochs as needed
    for batch_X, batch_y in dataloader:
        optimizer.zero_grad()
        print(batch_X.shape)
        predictions = model(batch_X)

        loss = criterion(predictions, batch_y)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch + 1}, Loss: {loss.item():.4f}")

import torch

# Function for inference
def predict_and_update(features_x, targets_y, model,window_size, target_column):
    """
    Predicts the next values given a window of past values and updates the dataframe.

    Args:
        df (pd.DataFrame): The dataframe containing input data.
        model (nn.Module): The trained TemporalSpatialTransformer model.
        window_size (int): The size of the input window for predictions.
        target_column (str): The column name of the target variable.

    Returns:
        predictions (list): Predicted values for the target column.
        ground_truth (list): Corresponding true values from the dataframe.
    """
    model.eval()  # Set model to evaluation mode
    predictions = []
    ground_truth = []

    # Iterate while there are enough rows for a full window + 1 value
    while len(features_x) > window_size:
        # Extract the input window
        input_window = features_x.iloc[:window_size].values
        true_value = targets_y.iloc[window_size]

        # Convert to tensor
        input_tensor = torch.tensor(input_window, dtype=torch.float32).unsqueeze(0)  # Add batch dimension

        # Make prediction
        with torch.no_grad():
            predicted_value = model(input_tensor).item()

        # Append the prediction and true value
        predictions.append(predicted_value)
        ground_truth.append(true_value)

        # Drop the row with the true value to simulate real-time prediction
        df = features_x.iloc[1:]  # Remove the first row (simulates data being consumed)

    return predictions, ground_truth

# Example usage
import pandas as pd

# Assuming `combined_all` is your dataframe
predictions, ground_truth = predict_and_update(combined_all_x.copy(),combined_all_y.copy(),model, window_size=2, target_column="Orbit Mean Density (kg/m^3)")

# Convert to DataFrame for comparison
results_df = pd.DataFrame({
    "Ground Truth": ground_truth,
    "Predictions": predictions
})

print(results_df)

