# -*- coding: utf-8 -*-
"""arc_comp_latest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2G-LoU39rZLV_-ZqKHTFHFp744PHeBC
"""

!pip install PythonAtmosphere

from google.colab import drive
drive.mount('/content/drive')

import orekit
from orekit.pyhelpers import setup_orekit_curdir, absolutedate_to_datetime,download_orekit_data_curdir

from org.orekit.orbits import KeplerianOrbit, EquinoctialOrbit, PositionAngleType, OrbitType, CartesianOrbit
from org.orekit.frames import FramesFactory, LOFType, Frame
from org.orekit.time import AbsoluteDate, TimeScalesFactory
from org.orekit.utils import Constants, PVCoordinates
from org.orekit.propagation.numerical import NumericalPropagator
from org.hipparchus.ode.nonstiff import DormandPrince853Integrator
from org.orekit.propagation import SpacecraftState
from org.orekit.bodies import OneAxisEllipsoid, CelestialBodyFactory, CelestialBody
from org.orekit.utils import IERSConventions
from org.orekit.forces.gravity.potential import GravityFieldFactory
from org.orekit.forces.gravity import HolmesFeatherstoneAttractionModel, ThirdBodyAttraction, OceanTides, SolidTides
from orekit import JArray_double, JArray
from java.util import ArrayList

from org.orekit.forces.radiation import SolarRadiationPressure, IsotropicRadiationSingleCoefficient, RadiationSensitive
from org.orekit.models.earth.atmosphere.data import CssiSpaceWeatherData, JB2008SpaceEnvironmentData
from org.orekit.forces.drag import IsotropicDrag, DragForce
from org.orekit.models.earth.atmosphere import DTM2000, HarrisPriester, JB2008, NRLMSISE00, Atmosphere, SimpleExponentialAtmosphere, PythonAtmosphere

from org.hipparchus.geometry.euclidean.threed import Vector3D

from math import radians, degrees, pi
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import animation
import time
import matplotlib.ticker as ticker
plt.rcParams.update({'font.size': 12})

vm = orekit.initVM()
setup_orekit_curdir()

setup_orekit_curdir(filename='/home/menah-hamman/Downloads/orekit-data.zip', from_pip_library=False)

import numpy as np

import os
import re
# Define the directory containing the files
directory = '/content/drive/MyDrive'

# List all files in the directory
all_files = os.listdir(directory)

# Filter files by category
initial_state_files = [f for f in all_files if f.endswith('initial_states.csv')]
omni2_files = [f for f in all_files if f.startswith('omni2-')]
goes_files = [f for f in all_files if f.startswith('goes-')]
champ_files = [f for f in all_files if f.endswith('.csv') and f not in initial_state_files + omni2_files + goes_files]

# Print the number of files in each category
print(f"Initial State Files: {len(initial_state_files)}")
print(f"OMNI2 Files: {len(omni2_files)}")
print(f"GOES Files: {len(goes_files)}")
print(f"Thermospheric Density Files: {len(champ_files)}")

initial_state_files = sorted(initial_state_files, key=lambda x: tuple(map(int, re.findall(r'\d+', x))))[:10]
omni2_files = sorted(omni2_files, key=lambda x: tuple(map(int, re.findall(r'\d+', x))))[:10]
goes_files = sorted(goes_files, key=lambda x: tuple(map(int, re.findall(r'\d+', x))))[:10]
champ_files = sorted(champ_files, key=lambda x: tuple(map(int, re.findall(r'\d+', x))))[:10]

import pandas as pd

# Load and sort initial state files
initial_state_dfs = []
for file in initial_state_files:
    df = pd.read_csv(os.path.join(directory, file))
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])  # Ensure Timestamp is in datetime format
    initial_state_dfs.append(df)

# Concatenate all initial state files
initial_state_df = pd.concat(initial_state_dfs).sort_values(by='Timestamp')

init = pd.read_csv(os.path.join(directory, initial_state_files[0]))

init

initial_state_df.head()

# Set Timestamp as the index

initial_state_df.set_index('Timestamp', inplace=True)

omni2_dfs = []
for file in omni2_files:
    df = pd.read_csv(os.path.join(directory, file))
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])  # Ensure Timestamp is in datetime format
    omni2_dfs.append(df)

# Concatenate all OMNI2 files
omni2_df = pd.concat(omni2_dfs).sort_values(by='Timestamp')

print(omni2_df)

# Load and sort GOES files
goes_dfs = []
for file in goes_files:
    df = pd.read_csv(os.path.join(directory, file))
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])  # Ensure Timestamp is in datetime format
    goes_dfs.append(df)

# Concatenate all GOES files
goes_df = pd.concat(goes_dfs).sort_values(by='Timestamp')

# Load and sort thermospheric density files
champ_dfs = []
for file in champ_files:
    df = pd.read_csv(os.path.join(directory, file))
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])  # Ensure Timestamp is in datetime format
    champ_dfs.append(df)

# Concatenate all thermospheric density files
champ_df = pd.concat(champ_dfs).sort_values(by='Timestamp')

from scipy.ndimage import gaussian_filter

# Resample GOES data to 5-minute bins
goes_df_resampled = goes_df.resample('5T', on='Timestamp').mean()
print(goes_df_resampled.columns)
print(goes_df_resampled['xrs_primary_chan'].head())
# Apply Gaussian smoothing (σ = 90 seconds)

goes_df_resampled = goes_df_resampled.dropna(axis=1, how='all')

# Fill NaNs with the mean of the column (required for Gaussian filter)
goes_df_resampled['xrsa_flux'] = goes_df_resampled['xrsa_flux'].fillna(goes_df_resampled['xrsa_flux'].mean())
goes_df_resampled['xrsb_flux'] = goes_df_resampled['xrsb_flux'].fillna(goes_df_resampled['xrsb_flux'].mean())

# Apply Gaussian filter to xrsa_flux and xrsb_flux
sigma = 1  # Standard deviation of the Gaussian kernel
goes_df_resampled['xrsa_flux_smoothed'] = gaussian_filter(goes_df_resampled['xrsa_flux'], sigma=sigma)
goes_df_resampled['xrsb_flux_smoothed'] = gaussian_filter(goes_df_resampled['xrsb_flux'], sigma=sigma)

initial_state_df

class CustomAtmosphere(PythonAtmosphere):
    """
    CustomAtmosphere is a custom implementation of the PythonAtmosphere class
    that uses the JB2008 atmospheric model to compute atmospheric density and
    velocity.

    Attributes:
        atm (JB2008): An instance of the JB2008 atmospheric model.
        earth (Body): The central body (Earth) for the atmospheric model.

    Methods:
        getDensity(date: AbsoluteDate, position: Vector3D, frame: Frame) -> float:
            Computes the atmospheric density at a given date, position, and frame.

        getVelocity(date: AbsoluteDate, position: Vector3D, frame: Frame) -> Vector3D:
            Computes the inertial velocity of atmosphere molecules at a given date,
            position, and frame. By default, the atmosphere is assumed to have a null
            velocity in the central body frame.
    """
    def __init__(self, cswl, sun, earth):
        super().__init__()
        # TODO for partcipants: initialize your atmospheric density model here
        self.atm = JB2008(cswl, sun, earth)
        self.earth = earth
    def getDensity(self, date: AbsoluteDate, position: Vector3D, frame: Frame):
        # TODO for partcipants: get the density from your model given date, position, and frame
        return self.atm.getDensity(date, position, frame)
    def getVelocity(self, date: AbsoluteDate, position: Vector3D, frame: Frame):
        '''
        Get the inertial velocity of atmosphere molecules.
        By default, atmosphere is supposed to have a null
        velocity in the central body frame.</p>
        '''
        # get the transform from body frame to the inertial frame
        bodyToFrame = self.earth.getBodyFrame().getKinematicTransformTo(frame, date)
        # Inverse transform the position to the body frame
        posInBody = bodyToFrame.getStaticInverse().transformPosition(position)
        # Create PVCoordinates object assuming zero velocity in body frame
        pv_body = PVCoordinates(posInBody, Vector3D.ZERO)
        # Transform the position/velocity (PV) coordinates to the given frame
        pvFrame = bodyToFrame.transformOnlyPV(pv_body)
        # Return the velocity in the current frame
        return pvFrame.getVelocity()

r_Earth = Constants.IERS2010_EARTH_EQUATORIAL_RADIUS #m
itrf    = FramesFactory.getITRF(IERSConventions.IERS_2010, True) # International Terrestrial Reference Frame, earth fixed
inertialFrame = FramesFactory.getEME2000()
earth = OneAxisEllipsoid(r_Earth,
                         Constants.IERS2010_EARTH_FLATTENING,
                         itrf)
mu = Constants.IERS2010_EARTH_MU #m^3/s^2
utc = TimeScalesFactory.getUTC()

def prop_orbit(initial_orbit, duration, step, CustomAtmosphereClass):
    """
    Propagates the orbit of a satellite over a given duration using a high-fidelity numerical propagator.
    Parameters:
    initial_orbit (Orbit): The initial orbit of the satellite.
    duration (float): The duration for which to propagate the orbit, in seconds.
    CustomAtmosphereClass (class): A custom atmosphere model class to be used for drag force calculations.
    Returns:
    tuple: A tuple containing:
        - states (list of SpacecraftState): The list of spacecraft states at each propagation step.
        - densities (list of float): The list of atmospheric densities at each spacecraft state.
    The function performs the following steps:
    1. Initializes the orbit parameters and spacecraft properties.
    2. Sets up the time span for propagation.
    3. Configures the numerical integrator and propagator.
    4. Adds force models to the propagator.
    5. Propagates the orbit over the specified duration.
    7. Plots the satellite trajectory in 3D.
    8. Computes atmospheric densities at each propagated state.
    """

    dur = duration # propagation duration time [s]
    satellite_mass = 260.0
    crossSection = 3.2 * 1.6 # m^2
    srpArea = 30.0 # m^2

    degree = 2
    torder = 2
    dragCoeff = 2.2
    cr = 1.0

    initialDate = initial_orbit.getDate()
    tspan = [initialDate.shiftedBy(float(dt)) for dt in np.linspace(0, duration, int(duration / step))]

    minStep = 1e-6
    maxstep = 1.0e4
    initStep = 1.0
    positionTolerance = 1e-3

    sun = CelestialBodyFactory.getSun()
    moon = CelestialBodyFactory.getMoon()

    satmodel = IsotropicDrag(crossSection, dragCoeff) # Cross sectional area and the drag coefficient

    initialOrbit = initial_orbit
    orbitType = initialOrbit.getType()
    initialState = SpacecraftState(initialOrbit, satellite_mass)
    tol = NumericalPropagator.tolerances(positionTolerance, initialOrbit, orbitType)

    integrator = DormandPrince853Integrator(minStep, maxstep, JArray_double.cast_(tol[0]), JArray_double.cast_(tol[1]))
    integrator.setInitialStepSize(initStep)

    propagator_num = NumericalPropagator(integrator)
    propagator_num.setOrbitType(orbitType)
    propagator_num.setInitialState(initialState)

    # Add Solar Radiation Pressure
    spacecraft = IsotropicRadiationSingleCoefficient(srpArea, cr)
    srpProvider = SolarRadiationPressure(sun, earth, spacecraft)
    propagator_num.addForceModel(srpProvider)

    # Add Gravity Force
    gravityProvider = GravityFieldFactory.getConstantNormalizedProvider(degree, torder, initialDate)
    gravityForce = HolmesFeatherstoneAttractionModel(earth.getBodyFrame(), gravityProvider)
    propagator_num.addForceModel(gravityForce)

    # Add Solid Tides
    solidTidesBodies = ArrayList().of_(CelestialBody)
    solidTidesBodies.add(sun)
    solidTidesBodies.add(moon)
    solidTidesBodies = solidTidesBodies.toArray()
    solidTides = SolidTides(earth.getBodyFrame(),
                            gravityProvider.getAe(), gravityProvider.getMu(),
                            gravityProvider.getTideSystem(),
                            IERSConventions.IERS_2010,
                            TimeScalesFactory.getUT1(IERSConventions.IERS_2010, True),
                            solidTidesBodies)
    propagator_num.addForceModel(solidTides)

    # Add Third Body Attractions
    propagator_num.addForceModel(ThirdBodyAttraction(sun))
    propagator_num.addForceModel(ThirdBodyAttraction(moon))

    # Add Custom Drag Force
    cswl = JB2008SpaceEnvironmentData("SOLFSMY.TXT", "DTCFILE.TXT")
    atmosphere = CustomAtmosphereClass(cswl, sun, earth)
    dragForce = DragForce(atmosphere, satmodel)
    propagator_num.addForceModel(dragForce)

    states = [initialState]
    tic = time.time()
    states = [propagator_num.propagate(tt)  for tt in tspan]
    toc = time.time()
    state.g
    posvel = [state.getPVCoordinates() for state in states]
    poss = [state.getPosition() for state in posvel]
    vels = [state.getVelocity() for state in posvel]
    px = [pos.getX() * 1e-3 for pos in poss]
    py = [pos.getY() * 1e-3 for pos in poss]
    pz = [pos.getZ() * 1e-3 for pos in poss]
    vx = [vel.getX() * 1e-3 for vel in vels]
    vy = [vel.getY() * 1e-3 for vel in vels]
    vz = [vel.getZ() * 1e-3 for vel in vels]
    stat_list = [dur, toc - tic, px[-1], py[-1], pz[-1], vx[-1], vy[-1], vz[-1], step]
    print("Time interval [s]:", stat_list[0])
    print("Time step [s]:", stat_list[8])
    print("CPU time [s]:", stat_list[1])
    print("Final Pos [km]:", np.linalg.norm([px[-1], py[-1], pz[-1]]))
    print("Final Vel [km]:", np.linalg.norm([vx[-1], vy[-1], vz[-1]]))

    # Plot the satellite trajectory
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot(px, py, pz, label='Trajectory')

    # plot earth
    phi = np.linspace(-np.pi, np.pi, 100)
    theta = np.linspace(-np.pi/2, np.pi/2, 50)
    X_Earth = r_Earth*1e-3 * np.outer(np.cos(phi), np.cos(theta)).T
    Y_Earth = r_Earth*1e-3 * np.outer(np.sin(phi), np.cos(theta)).T
    Z_Earth = r_Earth*1e-3 * np.outer(np.ones(np.size(phi)), np.sin(theta)).T
    ax.plot_surface(X_Earth, Y_Earth, Z_Earth, cmap='binary', alpha=0.35, antialiased=False, zorder = 1)

    ax.set_xlabel('X [km]')
    ax.set_ylabel('Y [km]')
    ax.set_zlabel('Z [km]')
    ax.set_aspect('equal', adjustable='box')
    ax.set_title('Satellite Trajectory')
    ax.legend()
    plt.show()

    densities = []
    for state in states:
        density = atmosphere.getDensity(state.getDate(), state.getPVCoordinates().getPosition(), state.getFrame())
        densities.append(density)

    return states, densities

from datetime import datetime
from org.orekit.time import TimeScalesFactory

def absolute_date_to_datetime(absolute_date):
    """Convert Orekit AbsoluteDate to Python datetime"""
    components = absolute_date.getComponents(TimeScalesFactory.getUTC())
    date = components.getDate()
    time_ = components.getTime()
    print(time_)
    print(type(time_))
    # Extract whole seconds and microseconds from fractional part
    seconds = int(time_.getSecond())  # Whole seconds
    microseconds = int((time_.getSecond() % 1) * 1_000_000)  # Convert fraction to microseconds

    return datetime(
        date.getYear(),
        date.getMonth(),
        date.getDay(),
        time_.getHour(),
        time_.getMinute(),
        seconds,
        microseconds  # Use microseconds instead of milliseconds
    )

from org.orekit.frames import Transform
from org.orekit.bodies import GeodeticPoint

def calculate_lat_lon(position, frame):
    """Calculate latitude and longitude from position vector"""
    earth = CelestialBodyFactory.getEarth()
    earth_transform = frame.getTransformTo(earth.getBodyFrame(), position.getDate())
    earth_position = earth_transform.transformPosition(position)

    geodetic_point = earth.getBodyShape().transform(earth_position, frame, position.getDate())
    return geodetic_point.getLatitude() * 180 / np.pi, geodetic_point.getLongitude() * 180 / np.pi

from org.orekit.orbits import KeplerianOrbit, PositionAngleType
from org.orekit.propagation.numerical import NumericalPropagator
from org.orekit.frames import FramesFactory
from org.orekit.time import AbsoluteDate, TimeScalesFactory
from org.orekit.utils import Constants
import numpy as np
import pandas as pd
from java.util import Date

def propagate_dataframe(initial_state_df, CustomAtmosphereClass):
    """
    Propagates between consecutive rows with 5-minute resampling
    Args:
        initial_state_df: DataFrame with Timestamp index and orbital elements
        CustomAtmosphereClass: Your atmosphere model class
    Returns:
        DataFrame with propagated states at 5-minute intervals between rows
    """
    # Constants
    mu = Constants.WGS84_EARTH_MU
    inertial_frame = FramesFactory.getEME2000()
    deg_to_rad = np.pi / 180

    duration = 86400.0  # 1 day in seconds
    step = 600.0       # 10 minutes in seconds

    all_results = []
    all_propagated = []

    for timestamp, row in initial_state_df.iterrows():
        iso_string = timestamp.strftime("%Y-%m-%dT%H:%M:%S.%f")

        # Create initial orbit
        initial_orbit = KeplerianOrbit(
            float(row['Semi-major Axis (km)'] * 1000),  # Convert km to m
            float(row['Eccentricity']),
            float(row['Inclination (deg)'] * deg_to_rad),
            float(row['Argument of Perigee (deg)'] * deg_to_rad),
            float(row['RAAN (deg)'] * deg_to_rad),
            float(row['True Anomaly (deg)'] * deg_to_rad),
            PositionAngleType.TRUE,
            inertial_frame,
            AbsoluteDate(iso_string, TimeScalesFactory.getUTC()),

            mu
        )




        #initial_orbit = EquinoctialOrbit(initial_orbit)


        states, densities = prop_orbit(initial_orbit, duration, step, CustomAtmosphere)

        #print(states,densities )

        # Create numerical propagator
        all_results.append((states, densities))

        # Extract and store Keplerian parameters at each step
        for state, density in zip(states, densities):
            orbit = state.getOrbit()
            if not isinstance(orbit, KeplerianOrbit):
                orbit = KeplerianOrbit.cast_(orbit)
                position = orbit.getPVCoordinates().getPosition()
                latitude, longitude = calculate_lat_lon(position, inertial_frame)
                       # Convert AbsoluteDate to Java Date then to Python datetime
            propagated_datetime = absolute_date_to_datetime(state.getDate())
            print(type(orbit))
            all_propagated.append({
                'Initial_Timestamp': timestamp,
                'Propagated_Timestamp': propagated_datetime, #state.getDate().toDate(),
                'Semi-major Axis (km)': orbit.getA() / 1000,
                'Eccentricity': orbit.getE(),
                'Inclination (deg)': orbit.getI() * 180 / np.pi,
                'RAAN (deg)': orbit.getRightAscensionOfAscendingNode() * 180 / np.pi,
                'Argument of Perigee (deg)': orbit.getPerigeeArgument() * 180 / np.pi,
                'True Anomaly (deg)': orbit.getTrueAnomaly() * 180 / np.pi,
                'Latitude (deg)': latitude #orbit.getPVCoordinates().getPosition().getLatitude() * 180 / np.pi,
                'Longitude (deg)': longitude # orbit.getPVCoordinates().getPosition().getLongitude() * 180 / np.pi,
                'Altitude (km)': (orbit.getPVCoordinates().getPosition().getNorm() - Constants.WGS84_EARTH_EQUATORIAL_RADIUS) / 1000,
                'Density (kg/m³)': density
            })

    # Create DataFrame
    result_df = pd.DataFrame(all_propagated)
    result_df['Propagated_Timestamp'] = pd.to_datetime(result_df['Propagated_Timestamp'])
    result_df.set_index(['Initial_Timestamp', 'Propagated_Timestamp'], inplace=True)

    return all_results, result_df

# initial_state_df = pd.read_csv('your_data.csv', parse_dates=['Timestamp'])
propagation_results, propagation_df = propagate_dataframe(initial_state_df, CustomAtmosphere)

# Access results for first initial state:
# states, densities = propagation_results[0]
# print(states[-1], densities[-1])  # Final state and density

nan_counts = goes_df_resampled.isna().sum()
print(nan_counts)
len(goes_df_resampled)

from scipy.ndimage import gaussian_filter

# Resample GOES data to 5-minute bins
goes_df_resampled = goes_df.resample('5T', on='Timestamp').mean()

# Apply Gaussian smoothing (σ = 90 seconds)

duplicate_timestamps = omni2_df.index.duplicated(keep=False)
duplicate_timestamps
#print(omni2_df[duplicate_timestamps].head(10))
omni2_df = omni2_df.groupby('Timestamp').mean()

omni2_df_upsampled = omni2_df.resample('5T').interpolate(method='cubic')

omni2_df_upsampled.index

# Shift OMNI2 data by 45 minutes
omni2_df_upsampled_shifted = omni2_df_upsampled.shift(periods=9, freq='5T')  # 45 minutes = 9 * 5 minutes

# Shift GOES data by 30 minutes
goes_df_resampled_shifted = goes_df_resampled.shift(periods=6, freq='5T')  # 30 minutes = 6 * 5 minutes

champ_df = champ_df.sort_values(by='Timestamp')

from org.orekit.orbits import KeplerianOrbit, PositionAngleType
from org.orekit.propagation.numerical import NumericalPropagator
from org.orekit.frames import FramesFactory
from org.orekit.time import AbsoluteDate, TimeScalesFactory
from org.orekit.utils import Constants
import numpy as np
import pandas as pd

# Constants
mu = Constants.WGS84_EARTH_MU
inertial_frame = FramesFactory.getEME2000()
deg_to_rad = np.pi / 180

def propagate_between_samples(initial_state_df, target_timestamps, CustomAtmosphereClass):
    """
    Propagate from initial states until target timestamps are reached
    Args:
        initial_state_df: DataFrame with initial orbital elements (one per row)
        target_timestamps: List/DatetimeIndex of when to stop propagation
        CustomAtmosphereClass: Your custom atmosphere model class
    Returns:
        List of (state, density) tuples at target timestamps
        DataFrame with Keplerian parameters at propagation steps
    """
    all_results = []
    keplerian_data = []

    # Convert target timestamps to AbsoluteDate
    target_dates = [AbsoluteDate(ts.year, ts.month, ts.day,
                               ts.hour, ts.minute, ts.second,
                               TimeScalesFactory.getUTC())
                   for ts in target_timestamps]

    for idx, (timestamp, row) in enumerate(initial_state_df.iterrows()):
        # Create initial Keplerian orbit
        initial_orbit = KeplerianOrbit(
            float(row['Semi-major Axis (km)'] * 1000),
            float(row['Eccentricity']),
            float(row['Inclination (deg)'] * deg_to_rad),
            float(row['Argument of Perigee (deg)'] * deg_to_rad),
            float(row['RAAN (deg)'] * deg_to_rad),
            float(row['True Anomaly (deg)'] * deg_to_rad),
            PositionAngleType.TRUE,
            inertial_frame,
            AbsoluteDate(timestamp.year, timestamp.month, timestamp.day,
                       timestamp.hour, timestamp.minute, timestamp.second,
                       TimeScalesFactory.getUTC()),

        )

        # Create numerical propagator with your force models
        propagator = create_numerical_propagator(initial_orbit, CustomAtmosphereClass)

        # Find next target timestamp
        if idx + 1 < len(target_timestamps):
            end_time = target_timestamps[idx+1]
            duration = (end_time - timestamp).total_seconds()

            # Propagate in 5-minute steps until target
            step = 300.0  # 5 minutes
            current_time = 0.0

            while current_time <= duration:
                state = propagator.propagate(
                    initial_orbit.getDate().shiftedBy(current_time)
                )
                density = get_atmospheric_density(state, CustomAtmosphereClass)

                # Store intermediate results
                keplerian_data.append(extract_keplerian_params(state, density))
                current_time += step

            # Get precise state at target time
            final_state = propagator.propagate(
                initial_orbit.getDate().shiftedBy(duration)
            )
            final_density = get_atmospheric_density(final_state, CustomAtmosphereClass)
            all_results.append((final_state, final_density))

    return all_results, pd.DataFrame(keplerian_data)

def create_numerical_propagator(orbit, CustomAtmosphereClass):
    """Your numerical propagator setup"""
    propagator = NumericalPropagator(orbit)
    # Add your force models (drag, SRP, gravity, etc.)
    # ... (your existing force model setup code)
    return propagator

def get_atmospheric_density(state, CustomAtmosphereClass):
    """Get atmospheric density at current state"""
    # Your density calculation code
    return density

def extract_keplerian_params(state, density):
    """Extract Keplerian parameters from state"""
    orbit = KeplerianOrbit.cast_(state.getOrbit())
    return {
        'datetime': state.getDate().toString(),
        'semi_major_axis_km': orbit.getA() / 1000,
        'eccentricity': orbit.getE(),
        # ... (other parameters)
        'density_kg_m3': density
    }

# Example usage:
# initial_state_df = pd.read_csv('initial_states.csv', parse_dates=['Timestamp'])
# target_timestamps = pd.date_range(start=..., end=..., freq=...)
# results, keplerian_df = propagate_between_samples(
#     initial_state_df,
#     target_timestamps,
#     JB2008Atmosphere
# )

# Merge datasets
merged_df = pd.merge_asof(champ_df, omni2_df_upsampled_shifted, on='Timestamp')
merged_df = pd.merge_asof(merged_df, goes_df_resampled_shifted, on='Timestamp')

# Log-transform SW_Plasma_Speed_km_s
merged_df['SW_Plasma_Speed_km_s_log'] = np.log(merged_df['SW_Plasma_Speed_km_s'])

# Signed cubic transform for BZ_nT_GSM
merged_df['BZ_nT_GSM_cubic'] = np.sign(merged_df['BZ_nT_GSM']) * np.abs(merged_df['BZ_nT_GSM']) ** 3

# Integrate XRS_flux over preceding 6 hours
merged_df['xrsa_flux_integral'] = merged_df['xrsa_flux'].rolling(window=72).sum()  # 6 hours = 72 * 5 minutes
merged_df['xrsb_flux_integral'] = merged_df['xrsb_flux'].rolling(window=72).sum()  # 6 hours = 72 * 5 minutes

# Check for NaNs in the new columns
print(merged_df[['SW_Plasma_Speed_km_s_log', 'BZ_nT_GSM_cubic', 'xrsa_flux_integral', 'xrsb_flux_integral']].isna().sum())

# Fill NaNs (if necessary)
merged_df['SW_Plasma_Speed_km_s_log'] = merged_df['SW_Plasma_Speed_km_s_log'].fillna(merged_df['SW_Plasma_Speed_km_s_log'].mean())
merged_df['BZ_nT_GSM_cubic'] = merged_df['BZ_nT_GSM_cubic'].fillna(merged_df['BZ_nT_GSM_cubic'].mean())
merged_df['xrsa_flux_integral'] = merged_df['xrsa_flux_integral'].fillna(merged_df['xrsa_flux_integral'].mean())
merged_df['xrsb_flux_integral'] = merged_df['xrsb_flux_integral'].fillna(merged_df['xrsb_flux_integral'].mean())



# Merge the resampled initial state data with merged_df
merged_df = pd.merge_asof(merged_df, initial_state_resampled_cleaned, on='Timestamp')

# Verify the merged DataFrame
print(merged_df.head())

merged_df = merged_df.fillna(method='ffill')  # Forward fill
merged_df = merged_df.fillna(method='bfill')  # Backward fill

merged_df.head()

# Convert latitude from degrees to radians
merged_df['Latitude_rad'] = np.radians(merged_df['Latitude (deg)'])

# Compute the scaling factor
merged_df['f_phi'] = 1 + 0.4 * np.abs(np.sin(merged_df['Latitude_rad']))
merged_df['True_Anomaly_rad'] = np.radians(merged_df['True Anomaly (deg)'])

# Compute the effective altitude
merged_df['h_eff'] = (
    merged_df['Semi-major Axis (km)'] * (1 - merged_df['Eccentricity'] ** 2)
) / (1 + merged_df['Eccentricity'] * np.cos(merged_df['True_Anomaly_rad']))

list(merged_df.columns)

merged_df['Time_diff'] = merged_df['Timestamp'].diff().dt.total_seconds()



features = [
    'SW_Plasma_Speed_km_s_log', 'BZ_nT_GSM_cubic', 'SW_Proton_Density_N_cm3',
    'SW_Plasma_Temperature_K', 'Flow_pressure', 'BX_nT_GSE_GSM', 'BY_nT_GSE',
    'BZ_nT_GSE', 'Plasma_Beta', 'Alfen_mach_number', 'Magnetosonic_Mach_number',
    'f10.7_index', 'R_Sunspot_No', 'Lyman_alpha', 'Proton_flux_>1_Mev',
    'Proton_flux_>2_Mev', 'Proton_flux_>4_Mev', 'Proton_flux_>10_Mev',
    'Proton_flux_>30_Mev', 'Proton_flux_>60_Mev', 'Kp_index', 'Dst_index_nT',
    'AE_index_nT', 'ap_index_nT', 'Semi-major Axis (km)', 'Eccentricity',
    'Inclination (deg)', 'Altitude (km)', 'f_phi', 'h_eff', 'xrsa_flux_integral',
    'xrsb_flux_integral'
]

# Drop irrelevant columns
columns_to_drop = [
     'File ID', 'YEAR', 'DOY', 'Hour', 'Bartels_rotation_number',
    'ID_for_IMF_spacecraft', 'ID_for_SW_Plasma_spacecraft', 'num_points_IMF_averages',
    'num_points_Plasma_averages', 'Flux_FLAG', 'xrsa_flag', 'xrsb_flag', 'xrsa_num',
    'xrsb_num', 'xrsa_flag_excluded', 'xrsb_flag_excluded', 'xrsa1_flag', 'xrsa2_flag',
    'xrsb1_flag', 'xrsb2_flag', 'xrsa1_num', 'xrsa2_num', 'xrsb1_num', 'xrsb2_num',
    'xrsa1_flag_excluded', 'xrsa2_flag_excluded', 'xrsb1_flag_excluded', 'xrsb2_flag_excluded',
    'yaw_flip_flag', 'xrsa_flux_observed', 'xrsb_flux_observed', 'xrsa_flux_electrons',
    'xrsb_flux_electrons', 'xrsa1_flux', 'xrsa1_flux_observed', 'xrsa1_flux_electrons',
    'xrsa2_flux', 'xrsa2_flux_observed', 'xrsa2_flux_electrons', 'xrsb1_flux',
    'xrsb1_flux_observed', 'xrsb1_flux_electrons', 'xrsb2_flux', 'xrsb2_flux_observed',
    'xrsb2_flux_electrons'
]

merged_df = merged_df.drop(columns=columns_to_drop)

# Verify the result
print("Original DataFrame:")
print(len(merged_df))
merged_df = merged_df.dropna()

# Reset the index (optional)
merged_df = merged_df.reset_index(drop=True)


print("\nCleaned DataFrame:")
print(len(merged_df))

# Extract initial orbital parameters from the first row of merged_df
semi_major_axis = merged_df['Semi-major Axis (km)'].iloc[0] * 1e3  # Convert km to meters
eccentricity = merged_df['Eccentricity'].iloc[0]
inclination = merged_df['Inclination (deg)'].iloc[0]
raan = merged_df['RAAN (deg)'].iloc[0]
arg_perigee = merged_df['Argument of Perigee (deg)'].iloc[0]
true_anomaly = merged_df['True Anomaly (deg)'].iloc[0]



semi_major_axis
eccentricity
inclination
raan
arg_perigee
true_anomaly

from org.orekit.orbits import KeplerianOrbit, PositionAngleType
from org.orekit.utils import Constants
from org.orekit.time import AbsoluteDate


from org.orekit.time import TimeScalesFactory
import numpy as np
inertialFrame = FramesFactory.getEME2000()

# Constants
r_Earth = Constants.IERS2010_EARTH_EQUATORIAL_RADIUS  # Earth's equatorial radius (m)
mu = Constants.IERS2010_EARTH_MU  # Earth's gravitational parameter (m^3/s^2)

# Convert angles from degrees to radians
deg = np.pi / 180
inclination_rad = inclination * deg
raan_rad = raan * deg
arg_perigee_rad = arg_perigee * deg
true_anomaly_rad = true_anomaly * deg

# Initial date (use the first timestamp from merged_df)
initialDate = AbsoluteDate(
    int(merged_df['Timestamp'].iloc[0].year),  # Ensure integer
    int(merged_df['Timestamp'].iloc[0].month),  # Ensure integer
    int(merged_df['Timestamp'].iloc[0].day),  # Ensure integer
    int(merged_df['Timestamp'].iloc[0].hour),  # Ensure integer
    int(merged_df['Timestamp'].iloc[0].minute),  # Ensure integer
    float(merged_df['Timestamp'].iloc[0].second),  # Ensure float
    TimeScalesFactory.getUTC()  # Time scale
)


utc_scale = TimeScalesFactory.getUTC()
print(utc_scale)
# Create initial orbit
initialOrbit = KeplerianOrbit(
    semi_major_axis,  # Semi-major axis (m)
    eccentricity,  # Eccentricity
    inclination_rad,  # Inclination (rad)
    arg_perigee_rad,  # Argument of Perigee (rad)
    raan_rad,  # Right Ascension of Ascending Node (rad)
    true_anomaly_rad,  # True Anomaly (rad)
    PositionAngleType.TRUE,  # Angle type
    inertialFrame,  # Inertial frame
    initialDate,  # Initial date
    mu  # Gravitational parameter
)

# Define features
features = [
    'SW_Plasma_Speed_km_s_log', 'BZ_nT_GSM_cubic', 'SW_Proton_Density_N_cm3',
    'SW_Plasma_Temperature_K', 'Flow_pressure', 'BX_nT_GSE_GSM', 'BY_nT_GSE',
    'BZ_nT_GSE', 'Plasma_Beta', 'Alfen_mach_number', 'Magnetosonic_Mach_number',
    'f10.7_index', 'R_Sunspot_No', 'Lyman_alpha', 'Proton_flux_>1_Mev',
    'Proton_flux_>2_Mev', 'Proton_flux_>4_Mev', 'Proton_flux_>10_Mev',
    'Proton_flux_>30_Mev', 'Proton_flux_>60_Mev', 'Kp_index', 'Dst_index_nT',
    'AE_index_nT', 'ap_index_nT', 'Semi-major Axis (km)', 'Eccentricity',
    'Inclination (deg)', 'Altitude (km)', 'f_phi', 'h_eff', 'xrsa_flux_integral',
    'xrsb_flux_integral'
]

# Define target
target = 'Orbit Mean Density (kg/m^3)'

# Create feature matrix (X) and target vector (y)
X = merged_df[features]
y = merged_df[target]