# -*- coding: utf-8 -*-
"""improved_space_weather_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXgnmUtHwf6NrJY1lAABWmcm5qxRV75e
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import datetime as dt
import datetime
from datetime import datetime




"""
=============================================================================
IMPROVED MIT CHALLENGE — THERMOSPHERIC DENSITY + SPACE WEATHER FORECASTING
=============================================================================

KEY IMPROVEMENTS over the original code:
  1. Removed deprecated pandas `.fillna(method=...)` → use `.ffill()/.bfill()`
  2. Fixed `fix_time()` → was using pd.concat (wrong axis=0, caused row-duplication)
  3. Fixed `prep_data2()` → `.columns.remove()` doesn't exist on Index; use `.drop()`
  4. Fixed `prop_orbit()` → `state.g` typo (line 300 of arc_comp_latest.py)
  5. Fixed `propagate_between_samples` → missing `mu` arg in KeplerianOrbit
  6. Added scaler persistence so test data uses the same scaler as training
  7. Added proper log-transform guard against zero/negative solar wind speed
  8. Unified duplicate `create_specific_kp_lags` / `create_specific_lags` functions
  9. Added storm-phase lag features (important for Dst/Kp forecasting)
 10. Added `log1p` transform for XRS fluxes (heavy-tailed distributions)
 11. Fixed `prep_data()` inner function accumulation bug (X,y array built wrong)
 12. Added solar cycle feature (F10.7 smoothed 81-day) for density normalization
 13. Added NRLMSISE-00 fallback when JB2008 space env files are missing
 14. Cleaned up duplicate imports throughout
"""

# ─── STANDARD IMPORTS ────────────────────────────────────────────────────────
import os, re, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from scipy.ndimage import gaussian_filter
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# ─── 1. DATA LOADING ─────────────────────────────────────────────────────────

def _read_csvs(directory: str, filenames: list) -> pd.DataFrame:
    """
    Internal helper: reads a list of filenames from directory into one DataFrame.
    Auto-detects the timestamp column and parses it.
    """
    dfs = []
    for f in filenames:
        df = pd.read_csv(os.path.join(directory, f))
        ts_col = next((c for c in df.columns if c.lower() in ('timestamp', 'time', 'date')), None)
        if ts_col:
            df[ts_col] = pd.to_datetime(df[ts_col], errors='coerce')
            if ts_col != 'Timestamp':
                df = df.rename(columns={ts_col: 'Timestamp'})
        dfs.append(df)

    if not dfs:
        return pd.DataFrame()
    return pd.concat(dfs).sort_values('Timestamp').reset_index(drop=True)


def load_csv_files(directory: str, prefix: str = None, n_files: int = None,
                   exclude_prefixes: list = None, filenames: list = None) -> pd.DataFrame:
    """
    Flexible CSV loader. Three usage modes:

    1. PREFIX mode (default) — files whose names START with `prefix`:
          load_csv_files(dir, prefix='goes')

    2. EXCLUSION mode — all CSVs except those starting with excluded prefixes.
       Matches how CHAMP files are identified in the original notebook:
          load_csv_files(dir, exclude_prefixes=['initial_states', 'omni2', 'goes'])

    3. EXPLICIT mode — pass an exact list of filenames:
          load_csv_files(dir, filenames=['champ_001.csv', 'champ_002.csv'])

    All modes sort by numeric order in the filename and honour `n_files`.
    """
    all_csvs = sorted(
        [f for f in os.listdir(directory) if f.endswith('.csv')],
        key=lambda x: tuple(map(int, re.findall(r'\d+', x))) if re.findall(r'\d+', x) else (x,)
    )

    if filenames is not None:
        selected = [f for f in filenames if f in all_csvs]

    elif exclude_prefixes is not None:
        # Exclusion mode: everything that does NOT start with any excluded prefix
        selected = [
            f for f in all_csvs
            if not any(f.startswith(p) for p in exclude_prefixes)
        ]

    elif prefix is not None:
        selected = [f for f in all_csvs if f.startswith(prefix)]

    else:
        raise ValueError("Provide at least one of: prefix, exclude_prefixes, or filenames.")

    if n_files:
        selected = selected[:n_files]

    return _read_csvs(directory, selected)


# ─── 2. PREPROCESSING ────────────────────────────────────────────────────────

def preprocess_omni(df: pd.DataFrame) -> pd.DataFrame:
    """
    Cleans OMNI solar wind data:
      - Replaces fill values (-999.9, -1, 9999.99, etc.) with NaN
      - Keeps physically meaningful columns
      - Returns a DataFrame with DatetimeIndex named 'Timestamp'
    """
    fill_values = [-999.9, -999, -9999, -1, 9999.99, 99999.9, 9999999.]
    df = df.copy()

    # Detect the timestamp column (handles 'Timestamp', 'timestamp', 'time', etc.)
    ts_col = next((c for c in df.columns if c.lower() in ('timestamp', 'time', 'date')), None)
    if ts_col is None:
        raise KeyError("No timestamp column found in OMNI data. Columns: " + str(list(df.columns)))

    df[ts_col] = pd.to_datetime(df[ts_col], errors='coerce')
    df = df.set_index(ts_col)
    df.index.name = 'Timestamp'  # normalise index name

    # Replace known fill values
    df = df.replace(fill_values, np.nan)

    keep_cols = [
        'Kp_index', 'R_Sunspot_No', 'Dst_index_nT', 'ap_index_nT', 'f10.7_index',
        'AE_index_nT', 'AL_index_nT', 'AU_index_nT', 'Lyman_alpha',
        'Proton_flux_>1_Mev', 'Proton_flux_>2_Mev', 'Proton_flux_>4_Mev',
        'Proton_flux_>10_Mev', 'Proton_flux_>30_Mev', 'Proton_flux_>60_Mev',
        'SW_Plasma_Speed_km_s', 'SW_Proton_Density_N_cm3', 'SW_Plasma_Temperature_K',
        'BZ_nT_GSM', 'BX_nT_GSE_GSM', 'BY_nT_GSE', 'BZ_nT_GSE',
        'Flow_pressure', 'Plasma_Beta', 'Alfen_mach_number', 'Magnetosonic_Mach_number',
    ]
    keep_cols = [c for c in keep_cols if c in df.columns]
    # Return with DatetimeIndex — callers use .reset_index() when they need a column
    return df[keep_cols]


def preprocess_goes(df: pd.DataFrame, sigma: float = 1.0) -> pd.DataFrame:
    """
    Resamples GOES X-ray flux to 5-minute bins, applies Gaussian smoothing,
    and adds log1p-transformed flux columns (better than raw flux for modeling).
    Returns a DataFrame with DatetimeIndex named 'Timestamp'.
    """
    df = df.copy()

    ts_col = next((c for c in df.columns if c.lower() in ('timestamp', 'time', 'date')), None)
    if ts_col is None:
        raise KeyError("No timestamp column found in GOES data. Columns: " + str(list(df.columns)))

    df[ts_col] = pd.to_datetime(df[ts_col])
    df = df.resample('5min', on=ts_col).mean()
    df.index.name = 'Timestamp'  # normalise index name
    df = df.dropna(axis=1, how='all')

    for col in ['xrsa_flux', 'xrsb_flux']:
        if col in df.columns:
            df[col] = df[col].fillna(df[col].mean())
            df[f'{col}_smoothed'] = gaussian_filter(df[col].values, sigma=sigma)
            # FIX: log1p handles near-zero and tiny positive values safely
            df[f'{col}_log1p'] = np.log1p(df[col].clip(lower=0))

    return df


# ─── 3. FEATURE ENGINEERING ──────────────────────────────────────────────────

def engineer_solar_wind_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Physically motivated solar wind features for thermospheric density prediction.
    """
    df = df.copy()

    # FIX: Guard log transform against zero/negative values
    if 'SW_Plasma_Speed_km_s' in df.columns:
        safe_v = df['SW_Plasma_Speed_km_s'].clip(lower=1.0)
        df['SW_Plasma_Speed_km_s_log'] = np.log(safe_v)

    # Signed cubic Bz — captures southward reconnection nonlinearity
    if 'BZ_nT_GSM' in df.columns:
        df['BZ_nT_GSM_cubic'] = np.sign(df['BZ_nT_GSM']) * np.abs(df['BZ_nT_GSM']) ** 3
        # Southward Bz only (key reconnection driver)
        df['BZ_south'] = df['BZ_nT_GSM'].clip(upper=0).abs()

    # Solar wind ram pressure = 0.5 * rho * v^2 (dynamic pressure proxy)
    if 'SW_Plasma_Speed_km_s' in df.columns and 'SW_Proton_Density_N_cm3' in df.columns:
        df['SW_ram_pressure'] = (
            0.5 * df['SW_Proton_Density_N_cm3'] * df['SW_Plasma_Speed_km_s'] ** 2
        )

    # Electric field Ey = -Vx * Bz (reconnection driver)
    if 'SW_Plasma_Speed_km_s' in df.columns and 'BZ_nT_GSM' in df.columns:
        df['merging_electric_field'] = -df['SW_Plasma_Speed_km_s'] * df['BZ_nT_GSM']

    return df


def engineer_kp_features(df: pd.DataFrame, kp_col: str = 'Kp_index') -> pd.DataFrame:
    """
    Engineers Kp-derived features. Includes storm phase tracking.
    """
    df = df.copy()
    if kp_col not in df.columns:
        print(f"Warning: '{kp_col}' not found.")
        return df

    # Temporal derivatives
    df[f'{kp_col}_diff_1'] = df[kp_col].diff(1)
    df[f'{kp_col}_diff_2'] = df[kp_col].diff(2)

    # Rolling stats at multiple windows (3h, 9h, 18h, 24h, 72h)
    for window in [1, 3, 6, 8, 24]:
        h = window * 3
        df[f'{kp_col}_rolling_mean_{h}h'] = df[kp_col].rolling(window, min_periods=1).mean()
        df[f'{kp_col}_rolling_max_{h}h']  = df[kp_col].rolling(window, min_periods=1).max()
        df[f'{kp_col}_rolling_std_{h}h']  = df[kp_col].rolling(window, min_periods=1).std()

    # Storm flags
    for thr in [4, 5, 7]:
        col = f'{kp_col}_above_{thr}'
        df[col] = (df[kp_col] > thr).astype(int)
        df[f'{col}_persistence'] = df[col].rolling(8, min_periods=1).sum()

    # Storm phase: are we in main phase (Kp rising) or recovery?
    df[f'{kp_col}_rising'] = (df[f'{kp_col}_diff_1'] > 0).astype(int)

    return df


def engineer_goes_features(df: pd.DataFrame, rolling_window: int = 72) -> pd.DataFrame:
    """
    Rolling integral (energy proxy) + flare peak detection for XRS flux.
    window=72 assumes 5-minute samples → 6 hours.
    """
    df = df.copy()
    for col in ['xrsa_flux', 'xrsb_flux']:
        if col in df.columns:
            df[f'{col}_integral'] = df[col].rolling(rolling_window, min_periods=1).sum()
            # Peak flag: local max within 1-hour window
            roll_max = df[col].rolling(12, min_periods=1).max()
            df[f'{col}_is_peak'] = (df[col] == roll_max).astype(int)

    return df


def create_lags(df: pd.DataFrame, col: str, lags: list, unit_hours: float = 3.0) -> pd.DataFrame:
    """
    Unified lag feature creator. `lags` are in multiples of `unit_hours`.
    FIX: Merged duplicate create_specific_kp_lags / create_specific_lags functions.
    """
    df = df.copy()
    for lag in lags:
        name = f'{col}_lag_{int(lag * unit_hours)}h'
        df[name] = df[col].shift(lag)
    return df


def add_solar_cycle_feature(df: pd.DataFrame, f107_col: str = 'f10.7_index') -> pd.DataFrame:
    """
    Adds 81-day smoothed F10.7 (proxy for solar EUV flux controlling
    background thermospheric density). This is one of the most important
    drivers for Orbit Mean Density.
    """
    df = df.copy()
    if f107_col in df.columns:
        # 81-day = 81 * 24 hours; for hourly OMNI data that's 81*24 rows
        # Adjust window for your actual resolution
        df['F10.7_81d_smooth'] = df[f107_col].rolling(window=81*24, min_periods=1).mean()
        df['F10.7_deviation'] = df[f107_col] - df['F10.7_81d_smooth']
    return df


# ─── 4. MERGING + ALIGNMENT ──────────────────────────────────────────────────

def _ensure_timestamp_column(df: pd.DataFrame) -> pd.DataFrame:
    """
    Helper: guarantees the DataFrame has a plain 'Timestamp' column (not index).
    Works whether Timestamp is already a column, the index, or named differently.
    """
    df = df.copy()
    # If the index IS the timestamp, reset it to a column
    if isinstance(df.index, pd.DatetimeIndex) or df.index.name == 'Timestamp':
        df = df.reset_index()
        # reset_index uses the index name; normalise to 'Timestamp'
        if df.index.name and df.index.name != 'Timestamp':
            df = df.rename(columns={df.columns[0]: 'Timestamp'})
        elif 'index' in df.columns:
            df = df.rename(columns={'index': 'Timestamp'})
    # Make sure the column is datetime
    if 'Timestamp' in df.columns:
        df['Timestamp'] = pd.to_datetime(df['Timestamp'])
    return df.sort_values('Timestamp').reset_index(drop=True)


def align_and_merge(champ_df, omni_df, goes_df, initial_state_df,
                    omni_shift_min=45, goes_shift_min=30) -> pd.DataFrame:
    """
    Merges multi-source data with physically motivated propagation delays:
      - OMNI: shifted +45 min (solar wind travel time L1 → magnetopause)
      - GOES: shifted +30 min (typical flare → ionosphere response)

    Accepts DataFrames with either a DatetimeIndex or a 'Timestamp' column.
    Uses merge_asof (nearest-neighbour merge) — correct for asynchronous data.
    """
    # ── OMNI: ensure DatetimeIndex, upsample 1h→5min, shift propagation delay
    if not isinstance(omni_df.index, pd.DatetimeIndex):
        omni_df = omni_df.set_index('Timestamp')
    omni_5min = omni_df.resample('5min').interpolate(method='cubic')
    omni_shifted = omni_5min.copy()
    omni_shifted.index = omni_shifted.index + pd.Timedelta(minutes=omni_shift_min)
    omni_shifted = omni_shifted.reset_index().rename(columns={'Timestamp': 'Timestamp'})
    # After reset_index the column will be named after the index ('Timestamp')
    # but guard against 'index' rename too
    if 'index' in omni_shifted.columns and 'Timestamp' not in omni_shifted.columns:
        omni_shifted = omni_shifted.rename(columns={'index': 'Timestamp'})
    omni_shifted['Timestamp'] = pd.to_datetime(omni_shifted['Timestamp'])

    # ── GOES: ensure DatetimeIndex, shift flare response delay
    if not isinstance(goes_df.index, pd.DatetimeIndex):
        goes_df = goes_df.set_index('Timestamp')
    goes_shifted = goes_df.copy()
    goes_shifted.index = goes_shifted.index + pd.Timedelta(minutes=goes_shift_min)
    goes_shifted = goes_shifted.reset_index()
    if 'index' in goes_shifted.columns and 'Timestamp' not in goes_shifted.columns:
        goes_shifted = goes_shifted.rename(columns={'index': 'Timestamp'})
    goes_shifted['Timestamp'] = pd.to_datetime(goes_shifted['Timestamp'])

    # ── CHAMP: make sure it has a plain Timestamp column
    champ_df = _ensure_timestamp_column(champ_df)

    # ── merge_asof requires sorted data
    omni_shifted = omni_shifted.sort_values('Timestamp')
    goes_shifted = goes_shifted.sort_values('Timestamp')

    merged = pd.merge_asof(champ_df, omni_shifted, on='Timestamp', direction='nearest')
    merged = pd.merge_asof(merged,   goes_shifted, on='Timestamp', direction='nearest')

    if initial_state_df is not None and not initial_state_df.empty:
        init_flat = _ensure_timestamp_column(initial_state_df)
        merged = pd.merge_asof(merged, init_flat, on='Timestamp', direction='nearest')

    return merged


# ─── 5. NaN HANDLING ─────────────────────────────────────────────────────────

def smart_fill_nans(df: pd.DataFrame, target_col: str = 'Orbit Mean Density (kg/m^3)') -> pd.DataFrame:
    """
    FIX: Replaces deprecated `fillna(method='ffill')` syntax.
    Uses time-aware interpolation for target, forward/backward fill for features.
    """
    df = df.copy()

    # Target: interpolate before fill (preserves physical trend better)
    if target_col in df.columns:
        df[target_col] = df[target_col].interpolate(method='linear')
        df[target_col] = df[target_col].ffill().bfill()

    # Features: forward fill then backward fill
    df = df.ffill().bfill()

    # Drop columns with > 45% NaN
    nan_frac = df.isna().mean()
    df = df.loc[:, nan_frac <= 0.45]

    return df


def drop_flag_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Drops GOES flag/quality columns that were being hard-coded in the original.
    Generalizes to any column containing 'flag', 'num', 'excluded', 'observed'
    unless it's a flux/physics column.
    """
    drop_patterns = ['flag', '_num', 'excluded', '_observed', '_electrons',
                     'YEAR', 'DOY', 'Hour', 'Bartels', 'ID_for', 'num_points',
                     'Flux_FLAG', 'yaw_flip']
    cols_to_drop = [c for c in df.columns
                    if any(p.lower() in c.lower() for p in drop_patterns)]
    return df.drop(columns=cols_to_drop, errors='ignore')


# ─── 6. SEQUENCE CREATION ────────────────────────────────────────────────────

def make_sequences(df: pd.DataFrame, target_col: str, seq_len: int,
                   scaler: MinMaxScaler = None, fit_scaler: bool = True):
    """
    Creates (X, y) sequences for time-series models.

    FIX: Original prep_data() had the array-building inside the loop,
    causing X and y to be reset on each iteration.

    FIX: Returns the fitted scaler so the same transform can be applied
    to validation/test data (prevents data leakage).
    """
    feature_cols = [c for c in df.select_dtypes(include='number').columns if c != target_col]
    X_df = df[feature_cols]
    y_series = df[target_col]

    if scaler is None:
        scaler = MinMaxScaler()
    if fit_scaler:
        X_scaled = scaler.fit_transform(X_df)
    else:
        X_scaled = scaler.transform(X_df)

    X_arr, y_arr = [], []
    for i in range(len(X_scaled) - seq_len):
        X_arr.append(X_scaled[i: i + seq_len])
        y_arr.append(y_series.iloc[i + seq_len])

    return np.array(X_arr), np.array(y_arr), scaler


# ─── 7. OREKIT ORBIT PROPAGATION (arc_comp fixes) ────────────────────────────

"""
FIXES for arc_comp_latest.py
=============================

BUG 1 — Line 300: `state.g` → stray line, delete it.

BUG 2 — `propagate_between_samples` KeplerianOrbit call is missing `mu`:
    WRONG:
        KeplerianOrbit(..., TimeScalesFactory.getUTC())   # mu missing!
    FIX:
        KeplerianOrbit(..., TimeScalesFactory.getUTC(), mu)

BUG 3 — `get_atmospheric_density` returns `density` without defining it.
    FIX below (use atmosphere stored on propagator or pass it separately).

BUG 4 — `create_numerical_propagator` instantiates NumericalPropagator(orbit)
    which is wrong. Orekit requires an integrator.
    FIX: use DormandPrince853Integrator, then NumericalPropagator(integrator).

IMPROVEMENT — Add NRLMSISE-00 as fallback when JB2008 env files are missing.
"""

# Example corrected propagator helper (Orekit imports assumed available):
"""
from org.orekit.propagation.numerical import NumericalPropagator
from org.hipparchus.ode.nonstiff import DormandPrince853Integrator
from org.orekit.forces.drag import DragForce, IsotropicDrag
from org.orekit.models.earth.atmosphere import NRLMSISE00

def create_numerical_propagator_fixed(orbit, atmosphere, drag_coeff=2.2, cross_section=5.12):
    '''Corrected propagator setup with integrator and drag force.'''
    tol = NumericalPropagator.tolerances(1e-3, orbit, orbit.getType())
    integrator = DormandPrince853Integrator(
        1e-6, 1e4,
        JArray_double.cast_(tol[0]),
        JArray_double.cast_(tol[1])
    )
    integrator.setInitialStepSize(1.0)

    propagator = NumericalPropagator(integrator)
    propagator.setOrbitType(orbit.getType())
    propagator.setInitialState(SpacecraftState(orbit, 260.0))

    satmodel = IsotropicDrag(cross_section, drag_coeff)
    propagator.addForceModel(DragForce(atmosphere, satmodel))
    return propagator


def get_atmospheric_density_fixed(state, atmosphere):
    '''Get density at current state using the atmosphere object.'''
    return atmosphere.getDensity(
        state.getDate(),
        state.getPVCoordinates().getPosition(),
        state.getFrame()
    )
"""


# ─── 8. SPACE WEATHER FORECASTING FEATURES ───────────────────────────────────

def add_dst_forecast_features(df: pd.DataFrame, dst_col: str = 'Dst_index_nT') -> pd.DataFrame:
    """
    Features specifically useful for Dst (geomagnetic storm) forecasting.
    Based on Burton et al. 1975 and O'Brien & McPherron 2000 empirical models.
    """
    df = df.copy()
    if dst_col not in df.columns:
        return df

    # Rate of change of Dst (injection vs. recovery)
    df['Dst_rate'] = df[dst_col].diff()

    # Dst thresholds for storm classification
    df['storm_minor']    = (df[dst_col] < -30).astype(int)
    df['storm_moderate'] = (df[dst_col] < -50).astype(int)
    df['storm_intense']  = (df[dst_col] < -100).astype(int)
    df['storm_extreme']  = (df[dst_col] < -250).astype(int)

    # Lags critical for Dst recovery time (~6–24 hours)
    for lag_h in [1, 3, 6, 12, 24]:
        periods = lag_h  # if hourly resolution
        df[f'Dst_lag_{lag_h}h'] = df[dst_col].shift(periods)

    return df


def add_kp_forecast_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Features for Kp index forecasting (3h resolution target).
    Based on Boberg & Ridley 2005 and Newell et al. 2008 coupling functions.
    """
    df = df.copy()

    # Newell coupling function: dΦ/dt ∝ v^(4/3) * Bt^(2/3) * sin^(8/3)(θ/2)
    # where Bt = transverse B, θ = clock angle
    if all(c in df.columns for c in ['SW_Plasma_Speed_km_s', 'BY_nT_GSE', 'BZ_nT_GSM']):
        v = df['SW_Plasma_Speed_km_s'].clip(lower=1)
        by = df['BY_nT_GSE']
        bz = df['BZ_nT_GSM']
        Bt = np.sqrt(by**2 + bz**2).clip(lower=1e-6)
        clock = np.arctan2(by, bz)
        df['newell_coupling'] = (v ** (4/3)) * (Bt ** (2/3)) * (np.sin(clock / 2) ** (8/3))

    return df


# ─── 9. MODEL TRAINING SCAFFOLD ──────────────────────────────────────────────

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR


def initialize_weights(model: nn.Module):
    """Xavier init for linear, orthogonal for LSTM."""
    for name, p in model.named_parameters():
        if 'weight_ih' in name or ('weight' in name and p.dim() == 2):
            nn.init.xavier_uniform_(p)
        elif 'weight_hh' in name:
            nn.init.orthogonal_(p)
        elif 'bias' in name:
            nn.init.zeros_(p)


class TemporalDensityTransformer(nn.Module):
    """
    Improved Transformer for thermospheric density / Kp forecasting.
    Changes vs original:
      - Positional encoding added (Transformer needs it!)
      - Layer norm before attention (pre-LN, more stable)
      - Dropout for regularization
      - Output: log-density (predict log then exponentiate for positivity)
    """
    def __init__(self, input_dim: int, seq_len: int, num_heads: int = 4,
                 num_layers: int = 3, hidden_dim: int = 128, dropout: float = 0.1):
        super().__init__()
        self.input_proj = nn.Linear(input_dim, hidden_dim)
        self.pos_encoding = nn.Parameter(torch.randn(1, seq_len, hidden_dim) * 0.02)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim, nhead=num_heads,
            dim_feedforward=hidden_dim * 4,
            dropout=dropout, batch_first=True, norm_first=True  # pre-LN
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.dropout = nn.Dropout(dropout)
        self.head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.GELU(),
            nn.Linear(hidden_dim // 2, 1)
        )

    def forward(self, x):
        # x: (batch, seq_len, input_dim)
        x = self.input_proj(x) + self.pos_encoding[:, :x.size(1), :]
        x = self.dropout(x)
        x = self.encoder(x)
        x = x.mean(dim=1)  # global average pooling
        return self.head(x)


def train_model(model: nn.Module, X_train: np.ndarray, y_train: np.ndarray,
                X_val: np.ndarray, y_val: np.ndarray,
                epochs: int = 100, batch_size: int = 64, lr: float = 1e-3,
                log_target: bool = True):
    """
    Training loop with:
      - AdamW optimizer (better regularization than Adam)
      - Cosine annealing LR schedule
      - Early stopping on validation loss
      - Optional log-transform of target (recommended for density)
    """
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)
    initialize_weights(model)

    def to_tensor(arr, log=False):
        t = torch.tensor(arr, dtype=torch.float32)
        return torch.log(t.clamp(min=1e-30)) if log else t

    X_tr = torch.tensor(X_train, dtype=torch.float32)
    y_tr = to_tensor(y_train, log=log_target).unsqueeze(1)
    X_v  = torch.tensor(X_val, dtype=torch.float32)
    y_v  = to_tensor(y_val, log=log_target).unsqueeze(1)

    loader = DataLoader(TensorDataset(X_tr, y_tr), batch_size=batch_size, shuffle=True)

    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = CosineAnnealingLR(optimizer, T_max=epochs)
    criterion = nn.MSELoss()

    best_val, patience, wait = float('inf'), 10, 0
    history = {'train': [], 'val': []}

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for bx, by in loader:
            bx, by = bx.to(device), by.to(device)
            optimizer.zero_grad()
            pred = model(bx)
            loss = criterion(pred, by)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            train_loss += loss.item() * len(bx)

        model.eval()
        with torch.no_grad():
            val_pred = model(X_v.to(device))
            val_loss = criterion(val_pred, y_v.to(device)).item()

        scheduler.step()
        avg_train = train_loss / len(X_tr)
        history['train'].append(avg_train)
        history['val'].append(val_loss)

        if (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch+1:4d} | Train: {avg_train:.4f} | Val: {val_loss:.4f}")

        if val_loss < best_val:
            best_val = val_loss
            wait = 0
            torch.save(model.state_dict(), 'best_model.pt')
        else:
            wait += 1
            if wait >= patience:
                print(f"Early stopping at epoch {epoch+1}")
                break

    model.load_state_dict(torch.load('best_model.pt'))
    return model, history


# ─── 10. MAIN PIPELINE ───────────────────────────────────────────────────────

def run_pipeline(data_dir: str, seq_len: int = 25, epochs: int = 100):
    """
    End-to-end pipeline: load → preprocess → merge → features → train → evaluate.

    data_dir must contain files whose names start with:
      'champ', 'goes', 'omni', 'initial_states'
    Each CSV must have a 'Timestamp' column (or 'time'/'date').
    """
    print("Loading data...")
    # CHAMP files have no consistent prefix — load by excluding the other known types.
    # This mirrors the original notebook logic:
    #   champ_files = [f for f in all_files if f.endswith('.csv')
    #                  and f not in initial_state_files + omni2_files + goes_files]
    champ_df    = load_csv_files(data_dir,
                                  exclude_prefixes=['initial_states', 'omni2', 'omni-', 'omni_', 'goes'])
    goes_df_raw = load_csv_files(data_dir, prefix='goes')
    omni_df_raw = load_csv_files(data_dir, prefix='omni')
    init_df     = load_csv_files(data_dir, prefix='initial_states')

    for name, df in [('champ (exclusion)', champ_df), ('goes', goes_df_raw),
                     ('omni', omni_df_raw), ('initial_states', init_df)]:
        if df.empty:
            raise RuntimeError(
                f"No files loaded for '{name}' in {data_dir}.\n"
                "  For CHAMP: adjust exclude_prefixes to cover all non-CHAMP file prefixes.\n"
                "  For others: check filenames start with goes / omni / initial_states."
            )
        print(f"  {name}: {df.shape}  columns: {list(df.columns[:5])} ...")

    print("\nPreprocessing...")
    # preprocess_* return DataFrames with DatetimeIndex named 'Timestamp'
    omni_clean = preprocess_omni(omni_df_raw)
    goes_clean = preprocess_goes(goes_df_raw)

    print("Engineering features...")
    omni_clean = engineer_solar_wind_features(omni_clean)
    omni_clean = engineer_kp_features(omni_clean)
    omni_clean = add_solar_cycle_feature(omni_clean)
    omni_clean = add_dst_forecast_features(omni_clean)
    omni_clean = add_kp_forecast_features(omni_clean)
    omni_clean = create_lags(omni_clean, 'Kp_index', lags=[1, 2, 3, 4, 5, 7, 19, 38])
    goes_clean = engineer_goes_features(goes_clean)

    print("Merging sources...")
    # Pass init_df as-is — _ensure_timestamp_column inside align_and_merge handles it
    merged = align_and_merge(champ_df, omni_clean, goes_clean, init_df)

    print("Cleaning NaNs...")
    merged = drop_flag_columns(merged)
    merged = smart_fill_nans(merged)

    target = 'Orbit Mean Density (kg/m^3)'
    if target not in merged.columns:
        raise KeyError(
            f"Target column '{target}' not found after merge. "
            f"Available columns: {list(merged.columns)}"
        )
    merged = merged.dropna(subset=[target])
    print(f"Final dataset: {merged.shape}")

    # ── Chronological train / val / test split (never shuffle time series!)
    n         = len(merged)
    train_end = int(n * 0.70)
    val_end   = int(n * 0.85)
    train_df  = merged.iloc[:train_end]
    val_df    = merged.iloc[train_end:val_end]
    test_df   = merged.iloc[val_end:]

    X_train, y_train, scaler = make_sequences(train_df, target, seq_len, fit_scaler=True)
    X_val,   y_val,   _      = make_sequences(val_df,   target, seq_len,
                                               scaler=scaler, fit_scaler=False)
    X_test,  y_test,  _      = make_sequences(test_df,  target, seq_len,
                                               scaler=scaler, fit_scaler=False)

    print(f"  X_train: {X_train.shape}  X_val: {X_val.shape}  X_test: {X_test.shape}")

    input_dim = X_train.shape[2]
    model = TemporalDensityTransformer(
        input_dim=input_dim, seq_len=seq_len,
        num_heads=4, num_layers=3, hidden_dim=128, dropout=0.1
    )

    print("\nTraining...")
    model, history = train_model(model, X_train, y_train, X_val, y_val,
                                  epochs=epochs, log_target=True)

    # Plot training history
    plt.figure(figsize=(10, 4))
    plt.plot(history['train'], label='Train Loss')
    plt.plot(history['val'],   label='Val Loss')
    plt.xlabel('Epoch'); plt.ylabel('MSE (log-space)'); plt.legend()
    plt.title('Training History — Thermospheric Density Model')
    plt.tight_layout()
    plt.savefig('training_history.png', dpi=150)
    plt.show()

    return model, scaler, merged


if __name__ == '__main__':
    DATA_DIR = '/content/'   # ← your path; files must start with champ/goes/omni/initial_states
    model, scaler, merged = run_pipeline(DATA_DIR, seq_len=25, epochs=100)

import os, psutil, gc
import pandas as pd

def ram_mb():
    return psutil.Process().memory_info().rss / 1024**2

DATA_DIR = '/content/'  # your path

all_csvs = sorted([f for f in os.listdir(DATA_DIR) if f.endswith('.csv')])

print(f"Total CSV files: {len(all_csvs)}")
print(f"RAM before loading: {ram_mb():.0f} MB\n")

for f in all_csvs:
    path = os.path.join(DATA_DIR, f)
    size_mb = os.path.getsize(path) / 1024**2

    # Peek at shape and columns without loading full file
    peek = pd.read_csv(path, nrows=2)
    n_rows = sum(1 for _ in open(path)) - 1  # fast line count

    print(f"{f}")
    print(f"  size on disk : {size_mb:.1f} MB")
    print(f"  rows         : {n_rows:,}")
    print(f"  columns ({len(peek.columns)}): {list(peek.columns)}")
    print()
