# -*- coding: utf-8 -*-
"""MIT_challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdbqvsPBYStzhfzUkf95J0K-3Y7aWTWH
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import datetime as dt
import datetime
from datetime import datetime

!pip install statsmodels

from sklearn.preprocessing import MinMaxScaler

import pandas as pd
"""
to drop
xrsb_flux_observed_x

xrsb_flag_x
xrsa_flag_x
xrsb_flux_electrons_x
xrsa_flux_electrons_x
"""



import pandas as pd
import numpy as np
import pandas as pd
import numpy as np

def engineer_kp_features(df, kp_col='Kp_index'):
    """
    Engineers a variety of features from the Kp index.

    Args:
        df (pd.DataFrame): DataFrame with a datetime index containing the Kp index.
        kp_col (str): Name of the Kp index column.

    Returns:
        pd.DataFrame: DataFrame with engineered Kp features added.
    """
    df_engineered = df.copy()

    if kp_col not in df_engineered.columns:
        print(f"Warning: Kp column '{kp_col}' not found.")
        return df_engineered

    # 1. Temporal Derivatives and Changes
    df_engineered[f'{kp_col}_diff_1'] = df_engineered[kp_col].diff(1)
    df_engineered[f'{kp_col}_diff_2'] = df_engineered[kp_col].diff(2)
    df_engineered[f'{kp_col}_rate_of_change_3h'] = df_engineered[kp_col].diff(1) # Assuming 3-hourly Kp

    # 2. Statistical Features over Windows (adjust window sizes as needed)
    for window in [3, 6, 8, 12, 24]: # Window sizes in number of 3-hour intervals (hours: 9, 18, 24, 36, 72)
        df_engineered[f'{kp_col}_rolling_mean_{window*3}h'] = df_engineered[kp_col].rolling(window=window, min_periods=1).mean()
        df_engineered[f'{kp_col}_rolling_std_{window*3}h'] = df_engineered[kp_col].rolling(window=window, min_periods=1).std()
        df_engineered[f'{kp_col}_rolling_min_{window*3}h'] = df_engineered[kp_col].rolling(window=window, min_periods=1).min()
        df_engineered[f'{kp_col}_rolling_max_{window*3}h'] = df_engineered[kp_col].rolling(window=window, min_periods=1).max()
        df_engineered[f'{kp_col}_rolling_q90_{window*3}h'] = df_engineered[kp_col].rolling(window=window, min_periods=1).quantile(0.9)

    # 3. Binary or Categorical Features (example thresholds)
    storm_thresholds = [4, 5, 7]
    for threshold in storm_thresholds:
        df_engineered[f'{kp_col}_above_{threshold}'] = (df_engineered[kp_col] > threshold).astype(int)
        df_engineered[f'{kp_col}_above_{threshold}_persistence'] = (df_engineered[f'{kp_col}_above_{threshold}']).rolling(window=8, min_periods=1).sum() # Check persistence over ~24 hours

    # (More advanced: Time since last storm - requires more complex logic to track events)

    return df_engineered





def create_engineered_features(df):
    """
    Adds engineered features to the input DataFrame.

    Args:
        df (pd.DataFrame): The input DataFrame containing the necessary columns.
                           Assumes columns 'SW_Plasma_Speed_km_s', 'BZ_nT_GSM',
                           'xrsa_flux', and 'xrsb_flux' exist.

    Returns:
        pd.DataFrame: The DataFrame with the following new features added:
                      - 'SW_Plasma_Speed_km_s_log': Log-transformed SW_Plasma_Speed_km_s
                      - 'BZ_nT_GSM_cubic': Signed cubic transform of BZ_nT_GSM
                      - 'xrsa_flux_integral': 6-hour integral of xrsa_flux (assuming 5-minute intervals)
                      - 'xrsb_flux_integral': 6-hour integral of xrsb_flux (assuming 5-minute intervals)
    """
    df_processed = df.copy()

    # Log-transform SW_Plasma_Speed_km_s
    if 'SW_Plasma_Speed_km_s' in df_processed.columns:
        df_processed['SW_Plasma_Speed_km_s_log'] = np.log(df_processed['SW_Plasma_Speed_km_s'].replace(0, np.nan)).fillna(method='ffill') # Replace 0 with NaN before log
    else:
        print("Warning: 'SW_Plasma_Speed_km_s' column not found.")

    # Signed cubic transform for BZ_nT_GSM
    if 'BZ_nT_GSM' in df_processed.columns:
        df_processed['BZ_nT_GSM_cubic'] = np.sign(df_processed['BZ_nT_GSM']) * np.abs(df_processed['BZ_nT_GSM']) ** 3
    else:
        print("Warning: 'BZ_nT_GSM' column not found.")

    # Integrate XRS_flux over preceding 6 hours (assuming 5-minute intervals)
    rolling_window = 72
    if 'xrsa_flux' in df_processed.columns:
        df_processed['xrsa_flux_integral'] = df_processed['xrsa_flux'].rolling(window=rolling_window, min_periods=1).sum().fillna(0)
    else:
        print("Warning: 'xrsa_flux' column not found.")

    if 'xrsb_flux' in df_processed.columns:
        df_processed['xrsb_flux_integral'] = df_processed['xrsb_flux'].rolling(window=rolling_window, min_periods=1).sum().fillna(0)
    else:
        print("Warning: 'xrsb_flux' column not found.")

    # It's generally better to fill NaNs *after* all feature engineering
    df_processed = df_processed.fillna(df_processed.mean(numeric_only=True))

    return df_processed

def create_specific_kp_lags(df, kp_col='Kp', lags=[1,2,3,4,5,7,19, 38]):
    """
    Creates specific lagged features for the Kp index based on provided lags.

    Args:
        df (pd.DataFrame): DataFrame with a datetime index containing the Kp index.
        kp_col (str): Name of the Kp index column.
        lags (list): List of integer lags (in 3-hour intervals).

    Returns:
        pd.DataFrame: DataFrame with the specified lagged Kp features added.
    """
    df_lagged = df.copy()
    for lag in lags:
        lag_col_name = f'{kp_col}_lag_{lag*3}h'
        df_lagged[lag_col_name] = df_lagged[kp_col].shift(lag)
    return df_lagged


def create_specific_lags(df, kp_col, lags):
    """
    Creates specific lagged features for the Kp index based on provided lags.

    Args:
        df (pd.DataFrame): DataFrame with a datetime index containing the Kp index.
        kp_col (str): Name of the Kp index column.
        lags (list): List of integer lags (in 3-hour intervals).

    Returns:
        pd.DataFrame: DataFrame with the specified lagged Kp features added.
    """
    df_lagged = df.copy()
    for lag in lags:
        lag_col_name = f'{kp_col}_lag_{lag*3}h'
        df_lagged[lag_col_name] = df_lagged[kp_col].shift(lag)
    return df_lagged

def drop_mostly_nan_columns(df, threshold=0.45):
    """
    Drops columns from a pandas DataFrame if the percentage of NaN values
    exceeds the specified threshold.

    Args:
        df (pd.DataFrame): The input DataFrame.
        threshold (float, optional): The threshold (between 0 and 1) for the
                                     maximum allowed percentage of NaN values.
                                     Defaults to 0.85.

    Returns:
        pd.DataFrame: A new DataFrame with columns exceeding the NaN
                      threshold dropped.
    """


    total_rows = len(df)
    columns_to_drop = []
    for col in df.columns:
        nan_count = df[col].isnull().sum()
        nan_percentage = nan_count / total_rows
        if nan_percentage > threshold:
            columns_to_drop.append(col)

    df_cleaned = df.drop(columns=columns_to_drop)
    df_cleaned.drop(["xrsb_flag_x","xrsa_flag_x"],axis=1,inplace=True)
    return df_cleaned

def choose_best_data_create_feats(merged_df):
  merged_df['SW_Plasma_Speed_km_s_log'] = np.log(merged_df['SW_Plasma_Speed_km_s'])

  merged_df['BZ_nT_GSM_cubic'] = np.sign(merged_df['BZ_nT_GSM']) * np.abs(merged_df['BZ_nT_GSM']) ** 3

  merged_df['xrsa_flux_integral'] = merged_df['xrsa_flux'].rolling(window=72).sum()  # 6 hours = 72 * 5 minutes
  merged_df['xrsb_flux_integral'] = merged_df['xrsb_flux'].rolling(window=72).sum()  # 6 hours = 72 * 5 minutes
  return  merged_df


def preprocess_omni_data(filepath):
    df1 = pd.read_csv(filepath, skiprows=0)

    df1['Timestamp'] = pd.to_datetime(df1['Timestamp'], errors='coerce')
    df1.set_index("Timestamp", inplace=True)

    print("index:", df1.index)
    print("columns:", df1.columns)
    print("Nanas",df1.isna().sum())
    print("len",len(df1))



    time_diffs = df1.index.to_series().diff().dropna()
    sampling_frequency = time_diffs.mode()[0]

    print("Sampling frequency:", sampling_frequency)

    # Drop rows with missing or non-numeric values in the critical columns
    df1 = df1.dropna(subset=["YEAR", "DOY", "Hour"]).copy()
    df1[["Year", "Day", "Hour"]] = df1[["YEAR", "DOY", "Hour"]].apply(pd.to_numeric, errors="coerce")



    data_n = df1[['Kp_index',
       'R_Sunspot_No', "Dst_index_nT","ap_index_nT", "f10.7_index",
       'AE_index_nT', 'AL_index_nT', 'AU_index_nT', 'pc_index', 'Lyman_alpha',
       'Proton_flux_>1_Mev', 'Proton_flux_>2_Mev', 'Proton_flux_>4_Mev',
       'Proton_flux_>10_Mev', 'Proton_flux_>30_Mev', 'Proton_flux_>60_Mev',
       'Flux_FLAG']]
    data_n = data_n.replace([-999.9, -1], np.nan)  # Replace missing or invalid values with NaN
    print("head:", data_n.head(3))

    print("OMNI data preprocessed successfully.")
    return data_n


def prep_data_choose_omni(df1, df2):

    # Ensure the index is datetime (if not already)
    df1.index = pd.to_datetime(df1.index)
    df2.index = pd.to_datetime(df2.index)

    # Resample to align timestamps (assuming 1-minute interval as an example)
    df1 = df1.resample('5T').mean()
    df2 = df2.resample('5T').mean()

    # Merge datasets by index
    #combined_df = pd.merge(df1, df2, left_index=True, right_index=True, how='outer')
    common_index = df1.index.union(df2.index)  # Create a union of indices
    df1 = df1.reindex(common_index)  # Reindex df1
    df2 = df2.reindex(common_index)  # Reindex df2
    #combined_df = pd.concat([df1, df2], axis=0)
    combined_df=pd.merge_asof(df1, df2, on='Timestamp')

    # Sort by index (timestamp)
    combined_df = combined_df.sort_index().reset_index()
    print("combined_df head",combined_df.head())
    # Handle missing values
    combined_df["Orbit Mean Density (kg/m^3)"] = combined_df['Orbit Mean Density (kg/m^3)'] \
        .interpolate(method='cubic').fillna(method='bfill').fillna(method='ffill')

    combined_df = combined_df.fillna(method='ffill').interpolate(method='cubic').fillna(method='bfill')

    # Normalize numerical columns except the target variable
    numerical_columns = ['xrsa_flux', 'xrsb_flux', 'xrsa_flux_observed', 'xrsb_flux_observed']
    scaler = MinMaxScaler()
    combined_df[numerical_columns] = scaler.fit_transform(combined_df[numerical_columns])

    return combined_df

"""

def prep_data_all(df1, df2):
    # Convert the index to datetime with error handling
    df1.index = pd.to_datetime(df1.index, errors='coerce')
    df2.index = pd.to_datetime(df2.index, errors='coerce')

    # Drop rows with NaT (invalid datetime) in the index
    df1 = df1[df1.index.notna()]
    df2 = df2[df2.index.notna()]

    # Resample to align timestamps (assuming 1-minute interval as an example)
    df1 = df1.resample('5min').mean()
    df2 = df2.resample('5min').mean()

    # Merge datasets by index
    #combined_df = pd.merge(df1, df2, left_index=True, right_index=True, how='outer')
    common_index = df1.index.union(df2.index)  # Create a union of indices
    df1 = df1.reindex(common_index)  # Reindex df1
    df2 = df2.reindex(common_index)  # Reindex df2
    #combined_df = pd.concat([df1, df2], axis=0)
    combined_df=pd.merge_asof(df1, df2, on='Timestamp')
    # Sort by index (timestamp)
    combined_df = combined_df.sort_index().reset_index()
    try:
      combined_df["Orbit Mean Density (kg/m^3)"] = combined_df['Orbit Mean Density (kg/m^3)'] \
        .interpolate(method='cubic').fillna(method='bfill').fillna(method='ffill')
    except:
      pass
    combined_df = combined_df.fillna(method='ffill').interpolate(method='cubic').fillna(method='bfill')

    # Handle Numeric Columns
    combined_df = combined_df.select_dtypes(include=['number'])
    to_predict=combined_df["Orbit Mean Density (kg/m^3)"].copy()
    # Normalize numerical columns except the target variable
    numerical_columns = combined_df.columns.drop('Orbit Mean Density (kg/m^3)', errors='ignore')
    scaler = MinMaxScaler()
    combined_df[numerical_columns] = scaler.fit_transform(combined_df[numerical_columns])

    return combined_df, to_predict
"""
def read_data(f):
  df1= pd.read_csv(f,skiprows=0)
  df1['Timestamp'] = pd.to_datetime(df1['Timestamp'], errors='coerce')
  df1.set_index("Timestamp", inplace=True)

  print("index:", df1.index)
  print("columns:", df1.columns)
  print("head:", df1.head(3))
  print("Nanas",df1.isna().sum())
  print("len",len(df1))

  #df1 = df1.resample('1T').mean()


  time_diffs = df1.index.to_series().diff().dropna()
  sampling_frequency = time_diffs.mode()[0]

  print("Sampling frequency:", sampling_frequency)
  return df1

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from statsmodels.tsa.stattools import ccf

import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import ccf

def remove_trend_polynomial(df, column, order=1):
    """
    Removes the trend from a specified column of a DataFrame using polynomial fitting.

    Args:
        df (pd.DataFrame): The input DataFrame with a datetime index.
        column (str): The name of the column to process.
        order (int): The order of the polynomial to fit (e.g., 1 for linear, 2 for quadratic).

    Returns:
        pd.DataFrame: A new DataFrame with the trend removed from the specified column.
    """
    df_detrended = df.copy()
    time = np.arange(len(df_detrended.index))
    coeffs = np.polyfit(time, df_detrended[column], order)
    trend = np.polyval(coeffs, time)
    df_detrended[column + '_detrended'] = df_detrended[column] - trend
    return df_detrended

# Example Usage:
# combined_all_detrended = remove_trend_polynomial(combined_all.copy(), 'Orbit Mean Density (kg/m^3)', order=1)
#



def remove_outliers_zscore(df, column, threshold=3):
    """
    Removes outliers from a specified column of a DataFrame using the Z-score method.

    Args:
        df (pd.DataFrame): The input DataFrame.
        column (str): The name of the column to process.
        threshold (float): The number of standard deviations from the mean to consider as an outlier.

    Returns:
        pd.DataFrame: A new DataFrame with outliers removed from the specified column.
    """
    df_cleaned = df.copy()
    z_scores = np.abs((df_cleaned[column] - df_cleaned[column].mean()) / df_cleaned[column].std())
    df_cleaned = df_cleaned[z_scores <= threshold]
    return df_cleaned

# Example Usage:
# combined_all_cleaned = remove_outliers_zscore(combined_all.copy(), 'Orbit Mean Density (kg/m^3)', threshold=3)
def keep_highest_correlation(df, target_column, percentage=0.5, threshold=None, absolute=True):
    """
    Keeps the top percentage of columns with the highest correlation (or above a
    threshold) to the specified target variable in a pandas DataFrame.

    Args:
        df (pd.DataFrame): The input DataFrame.
        target_column (str): The name of the target variable column.
        percentage (float, optional): The percentage (between 0 and 1) of top
                                     correlated columns to keep. For example,
                                     0.5 keeps the top 50% of features.
                                     Defaults to 0.5.
        threshold (float, optional): A minimum absolute correlation value to keep
                                     columns. If provided, this takes precedence
                                     over the percentage. Only columns with an
                                     absolute correlation greater than or equal to
                                     this threshold are kept. Defaults to None.
        absolute (bool, optional): Whether to consider the absolute value of the
                                   correlation. If True (default), the magnitude
                                   of the correlation is used. If False, the
                                   sign of the correlation is considered.

    Returns:
        pd.DataFrame: A new DataFrame containing only the target column and the
                      top correlated columns (based on the percentage or
                      threshold).
    """
    if target_column not in df.columns:
        raise ValueError(f"Target column '{target_column}' not found in DataFrame.")

    correlations = df.corr()[target_column].drop(target_column)

    if absolute:
        correlations = correlations.abs()

    if threshold is not None:
        relevant_correlations = correlations[correlations >= threshold]
        top_correlated_columns = relevant_correlations.sort_values(ascending=False).index.tolist()
    else:
        num_features = len(correlations)
        n_to_keep = max(1, int(percentage * num_features))  # Ensure at least one feature is kept
        top_correlated_columns = correlations.nlargest(n_to_keep).index.tolist()

    columns_to_keep = [target_column] + top_correlated_columns
    # Ensure only existing columns are kept
    columns_to_keep = [col for col in columns_to_keep if col in df.columns]

    return df[columns_to_keep].copy()

def prep_data_all(df_list):
    """
    Combines a list of pandas DataFrames based on their time indices,
    aligns timestamps, handles missing values, and normalizes numerical columns.

    Args:
        df_list (list): A list of pandas DataFrames with datetime indices.

    Returns:
        tuple: A tuple containing:
            - combined_df (pandas.DataFrame): The merged and preprocessed DataFrame.
            - to_predict (pandas.Series): The target variable ('Orbit Mean Density (kg/m^3)').
    """
    if not df_list:
        return pd.DataFrame(), pd.Series()

    # Convert index to datetime and drop NaT
    processed_dfs = []
    for df in df_list:
        df.index = pd.to_datetime(df.index, errors='coerce')
        df = df[df.index.notna()]
        processed_dfs.append(df.resample('5min').mean()) # Resample each DataFrame

    # Merge all DataFrames based on the union of their indices
    if not processed_dfs:
        return pd.DataFrame(), pd.Series()

    combined_index = processed_dfs[0].index
    for df in processed_dfs[1:]:
        combined_index = combined_index.union(df.index)

    merged_df = pd.DataFrame(index=combined_index)
    for df in processed_dfs:
        merged_df = merged_df.merge(df, left_index=True, right_index=True, how='left')

    combined_df = merged_df.sort_index().reset_index().rename(columns={'index': 'Timestamp'})

    try:
        combined_df["Orbit Mean Density (kg/m^3)"] = combined_df['Orbit Mean Density (kg/m^3)'] \
            .interpolate(method='linear').fillna(method='bfill').fillna(method='ffill')
    except KeyError:
        pass  # Handle case where target column might be missing

    combined_df = combined_df.fillna(method='ffill').interpolate(method='linear').fillna(method='bfill')
    print("combined_df head",combined_df.head())
    # Handle Numeric Columns
    numeric_df = combined_df.select_dtypes(include=['number']).copy()
    to_predict = numeric_df["Orbit Mean Density (kg/m^3)_x"].copy()
    #numeric_df = numeric_df.drop(["Orbit Mean Density (kg/m^3)_x","Orbit Mean Density (kg/m^3)_y"], errors='ignore')
    numeric_df = numeric_df.drop(["Orbit Mean Density (kg/m^3)_x"], errors='ignore')
    # Normalize numerical columns
    numerical_columns = numeric_df.columns
    if not numerical_columns.empty:
        scaler = MinMaxScaler()
        numeric_df[numerical_columns] = scaler.fit_transform(numeric_df[numerical_columns])

    # Re-insert the target variable if it existed

    return numeric_df



import pandas as pd
import numpy as np

def drop_zero_rows_cols(df):
    """
    Drops rows where all values are zero and columns where all values are zero.

    Args:
        df (pd.DataFrame): The input DataFrame.

    Returns:
        pd.DataFrame: The DataFrame with zero rows and zero columns removed.
    """
    # Drop rows where all values are zero
    df_cleaned_rows = df[(df != 0).any(axis=1)]

    # Drop columns where all values are zero
    df_cleaned_cols = df_cleaned_rows.loc[:, (df_cleaned_rows != 0).any(axis=0)]

    return df_cleaned_cols






def create_lagged_target_features(df, target_column='Orbit Mean Density (kg/m^3)_x', lookbacks=[1,39, 41]):
    """
    Creates new feature columns by taking lagged values of the target column.

    Args:
        df (pd.DataFrame): The input DataFrame with a datetime index.
        target_column (str): The name of the target variable column.
        lookbacks (list): A list of integer values representing the number of
                          time steps to look back for creating lagged features.

    Returns:
        pd.DataFrame: The DataFrame with new lagged target feature columns added.
    """
    df_with_lags = df.copy()
    for lag in lookbacks:
        lag_column_name = f'{target_column}_lag_{lag}'
        df_with_lags[lag_column_name] = df_with_lags[target_column].shift(lag)
        df_with_lags.fillna(0,inplace=True) #bfill().ffill()  # Fill NaN values with 0
    return df_with_lags



import pandas as pd
import numpy as np
#choseeeeeee features ----
def select_top_features(df, feature_importances, top_n=None):
    """
    Selects the top N most important features from a DataFrame based on
    feature importance scores.

    Args:
        df (pd.DataFrame): The input DataFrame containing all features.
        feature_importances (dict): A dictionary where keys are feature names
                                     and values are their importance scores.
        top_n (int, optional): The number of top features to select.
                                 If None, all features in feature_importances
                                 will be kept. Defaults to None.

    Returns:
        pd.DataFrame: A new DataFrame containing only the selected top features.
    """
    sorted_importances = sorted(feature_importances.items(), key=lambda item: item[1], reverse=True)
    selected_features = [item[0] for item in sorted_importances[:top_n]]
    return df[selected_features].copy()

def create_and_drop_features(df, feature_importances, top_n=None):
    """
    Creates a new DataFrame containing the top N most important features
    and drops the rest from the original DataFrame.

    Args:
        df (pd.DataFrame): The original DataFrame.
        feature_importances (dict): A dictionary of feature names and their
                                     importance scores.
        top_n (int, optional): The number of top features to keep.
                                 If None, all features in feature_importances
                                 will be kept. Defaults to None.

    Returns:
        pd.DataFrame: A new DataFrame with only the selected top features.
    """
    return select_top_features(df, feature_importances, top_n)

# --- Example Usage (assuming you have your DataFrame 'combined_all_x_c_full' and 'feature_importance' dict) ---

# Sample DataFrame (replace with your actual DataFrame)





def examine_cross_correlation(df, kp_col='Kp', target_col='Orbit Mean Density (kg/m^3)', lags=40):
    if kp_col not in df.columns or target_col not in df.columns:
        print(f"Error: '{kp_col}' or '{target_col}' column not found in the DataFrame.")
        return None




    # Extract the aligned values
    kp_values = df[kp_col].values
    target_values = df[target_col].values
    print(len(kp_values))
    print(len(target_values))

    # Compute cross-correlation
    cross_corr = ccf(target_values, kp_values, nlags=lags)

    # Create a DataFrame to display the results
    lag_indices = np.arange(-lags, lags + 1)
    ccf_df = pd.DataFrame({'Lag': lag_indices, 'Cross-Correlation': cross_corr})
    ccf_df = ccf_df.set_index('Lag')

    # Plot the cross-correlation function
    plt.figure(figsize=(10, 6))
    plt.stem(lag_indices, cross_corr, use_line_collection=True)
    plt.title(f'Cross-Correlation Function (CCF) between {target_col} and Lagged {kp_col}')
    plt.xlabel('Lag (in time units of your data)')
    plt.ylabel('Cross-Correlation Coefficient')
    plt.grid(True)
    plt.show()

    print("\nCross-Correlation Coefficients:")
    print(ccf_df)

    return ccf_df
def examine_cross_correlation(df, kp_col, target_col, lags):
    """
    Examines the cross-correlation of a target column with itself (at different lags)
    within a pandas DataFrame, optionally grouped by a Kp index.

    Args:
        df (pd.DataFrame): The input DataFrame.
        kp_col (str, optional): The name of the column to group by (e.g., 'Kp_index').
                                 If None, cross-correlation is calculated on the entire DataFrame.
        target_col (str): The name of the target column for cross-correlation.
        lags (int): The maximum number of lags to consider (positive and negative).

    Returns:
        pd.DataFrame: A DataFrame containing the cross-correlation results.
                      Columns will include 'Kp_index' (if grouping), 'Lag', and 'Cross-Correlation'.
    """
    results = []

    if kp_col:
        for kp_value in df[kp_col].unique():
            group = df[df[kp_col] == kp_value].sort_values(df.index.name if df.index.name else df.columns[0]) # Ensure data is sorted
            target_series = group[target_col]
            if len(target_series) < 2:
                continue  # Cannot calculate correlation with less than 2 data points

            # Calculate cross-correlation with itself for the specified lags
            n = len(target_series)
            mean = target_series.mean()
            std = target_series.std()

            if std == 0:
                continue # Cannot calculate correlation if standard deviation is zero

            for lag in range(-lags, lags + 1):
                shifted_series = target_series.shift(lag)
                if lag > 0:
                    valid_indices = target_series.index[:-lag]
                    y1 = target_series.loc[valid_indices]
                    y2 = shifted_series.loc[valid_indices]
                elif lag < 0:
                    valid_indices = target_series.index[-lag:]
                    y1 = target_series.loc[valid_indices]
                    y2 = shifted_series.loc[valid_indices]
                else:
                    y1 = target_series
                    y2 = shifted_series

                if len(y1) > 1 and y2.notna().all(): # Ensure there are valid overlapping points
                    correlation = np.corrcoef(y1, y2)[0, 1]
                    results.append({'Kp_index': kp_value, 'Lag': lag, 'Cross-Correlation': correlation})
                elif lag == 0:
                    results.append({'Kp_index': kp_value, 'Lag': lag, 'Cross-Correlation': 1.0}) # Correlation with itself at lag 0 is 1

    else:
        # Calculate cross-correlation on the entire DataFrame
        target_series = df[target_col].sort_values(df.index.name if df.index.name else df.columns[0]) # Ensure data is sorted
        if len(target_series) < 2:
            return pd.DataFrame(results)

        n = len(target_series)
        mean = target_series.mean()
        std = target_series.std()

        if std == 0:
            return pd.DataFrame(results)

        for lag in range(-lags, lags + 1):
            shifted_series = target_series.shift(lag)
            if lag > 0:
                valid_indices = target_series.index[:-lag]
                y1 = target_series.loc[valid_indices]
                y2 = shifted_series.loc[valid_indices]
            elif lag < 0:
                valid_indices = target_series.index[-lag:]
                y1 = target_series.loc[valid_indices]
                y2 = shifted_series.loc[valid_indices]
            else:
                y1 = target_series
                y2 = shifted_series

            if len(y1) > 1 and y2.notna().all():
                correlation = np.corrcoef(y1, y2)[0, 1]
                results.append({'Lag': lag, 'Cross-Correlation': correlation})
            elif lag == 0:
                results.append({'Lag': lag, 'Cross-Correlation': 1.0})

    return pd.DataFrame(results)
# Example Usage (assuming you have a DataFrame 'space_weather_data'
# with 'Kp' and 'Orbit Mean Density (kg/m^3)' columns and a datetime index):
# ccf_results = examine_cross_correlation(
#     space_weather_data.copy(),
#     kp_col='Kp',
#     target_col='Orbit Mean Density (kg/m^3)',
#     lags=40  # Adjust the number of lags to examine
# )

# If ccf_results is not None:
#     # Identify lags with high absolute cross-correlation
#     high_corr_lags = ccf_results[abs(ccf_results['Cross-Correlation']) > 0.2].index.tolist() # Example threshold
#     print("\nLags with potentially high cross-correlation (example threshold):", high_corr_lags)

df_c1=read_data("/content/drive/MyDrive/champ_-00003-20000806_to_20000809.csv")

df_c2=read_data("/content/drive/MyDrive/champ_-00029-20001019_to_20001022.csv")

df_g1=read_data("/content/drive/MyDrive/goes-00004-20000609_to_20000808.csv")

df_g2=read_data("/content/drive/MyDrive/goes-00017-20000727_to_20000925.csv")

df_g3=read_data("/content/drive/MyDrive/goes-00019-20000801_to_20000930.csv")

df_g3=read_data("/content/drive/MyDrive/goes-00037-20000901_to_20001031.csv")

df_o1=preprocess_omni_data("/content/drive/MyDrive/omni2-00001-20000604_to_20000803.csv")

df_o2=preprocess_omni_data("/content/drive/MyDrive/omni2-00002-20000606_to_20000805.csv")

df_o3=preprocess_omni_data("/content/drive/MyDrive/omni2-00009-20000708_to_20000906.csv")

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

df_list=[ df_g1, df_g2, df_g3, df_o1, df_o2, df_o3,df_c1, df_c2]
resample_freq='3D'
nan_threshold=0.8

combined=prep_data_all(df_list)
combined_engineered = create_engineered_features(combined.copy())
space_weather_data_engineered = engineer_kp_features(combined_engineered.copy())

combined_all_y=combined["Orbit Mean Density (kg/m^3)_x"]
#combined_all_corr=keep_highest_correlation(combined, "Orbit Mean Density (kg/m^3)_x", percentage=0.5,threshold=0.2)
combined_all_x_1=space_weather_data_engineered.copy().drop(["Orbit Mean Density (kg/m^3)_y"],axis=1)
combined_all_x = create_specific_kp_lags(combined_all_x_1.copy(), kp_col='Kp_index', lags=[1,2,3,5,6,7,18,38])

combined_all_x = create_specific_lags(combined_all_x.copy(), kp_col='Dst_index_nT_x', lags=[22])
combined_all_x = create_specific_lags(combined_all_x.copy(), kp_col='AL_index_nT_x', lags=[8])



#combined_all_x_c=choose_best_data_create_feats(combined_all_x)
combined_all_x_c_full=create_lagged_target_features(combined_all_x)

combined_all_x_c_full=drop_zero_rows_cols(combined_all_x_c_full)
print("combined_all_x_c_full",combined_all_x_c_full.columns)
combined_all_x_c_full=drop_mostly_nan_columns(combined_all_x_c_full, threshold=0.95)
combined_all_x_c_full=remove_trend_polynomial(combined_all_x_c_full, 'Orbit Mean Density (kg/m^3)_x', order=1)
combined_all_x_c_full=remove_outliers_zscore(combined_all_x_c_full, 'Orbit Mean Density (kg/m^3)_x', threshold=3)
print(combined_all_x_c_full.shape)

combined_engineered.head()

len(combined_all_x_c_full.columns)

combined_all_x_c_full.isna().sum()

type(combined.corr())

print("Dataset Shape:", combined_all_x.shape)
print("Columns:", combined_all_x.columns)

# Check for missing values
print("Missing Values:\n", combined_all_x_c_full.isnull().sum())

from statsmodels.tsa.stattools import acf, pacf

# Calculate ACF and PACF
acf_values = acf(combined_all_y, nlags=30)
pacf_values = pacf(combined_all_y, nlags=30, method="ywm")

print("ACF Values:", acf_values)
print("PACF Values:", pacf_values)



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
plt.figure(figsize=(12, 6))

# Autocorrelation Function
plt.subplot(2, 1, 1)
plot_acf(combined_all_y, lags=60, ax=plt.gca())
plt.title("Autocorrelation Function (ACF)")

# Partial Autocorrelation Function
plt.subplot(2, 1, 2)
plot_pacf(combined_all_y, lags=60, ax=plt.gca(), method="ywm")
plt.title("Partial Autocorrelation Function (PACF)")

plt.tight_layout()
plt.show()

from statsmodels.tsa.stattools import adfuller

orbit_density_diff = combined_all_y.diff().dropna() # .dropna() removes the first NaN value created by differencing

# Now you would run the ADF test again on 'orbit_density_diff' to see if it's stationary
result_diff = adfuller(orbit_density_diff)
print('\nADF Test after First-Order Differencing:')
print('ADF Statistic:', result_diff[0])
print('p-value:', result_diff[1])
print('Critical Values:', result_diff[4])
if result_diff[1] <= 0.05:
    print('The differenced data is likely stationary.')
else:
    print('The differenced data is likely non-stationary.')

plot_pacf(combined_all_x_c_full['Kp_index'], lags=60) # Adjust 'lags' as needed
plt.title('PACF of Kp Index')
plt.xlabel('Lag (in 3-hour intervals)')
plt.ylabel('Partial Autocorrelation')
plt.show()

ccf_results = examine_cross_correlation(
     combined_all_x_c_full.copy(),
     kp_col='Kp_index',
     target_col="Orbit Mean Density (kg/m^3)_x",
     lags=40  )

if ccf_results is not None:
     # Identify lags with high absolute cross-correlation
     high_corr_lags = ccf_results[abs(ccf_results['Cross-Correlation']) > 0.2].index.tolist()
     print("\nLags with potentially high cross-correlation (example threshold):", high_corr_lags)

combined_all_x_c_full.columns

ccf_results = examine_cross_correlation(
     space_weather_data_engineered.copy(),
     kp_col='AL_index_nT_x',
     target_col="Orbit Mean Density (kg/m^3)_x",
     lags=40  )
#SW_Plasma_Speed_km_s
if ccf_results is not None:
     # Identify lags with high absolute cross-correlation
     high_corr_lags = ccf_results[abs(ccf_results['Cross-Correlation']) > 0.2].index.tolist()
     print("\nLags with potentially high cross-correlation (example threshold):", high_corr_lags)

data = combined_all_x_c_full
columns = [f'Feature_{i}' for i in range(95)]
combined_all_x_c_full = pd.DataFrame(data, columns=columns)

# Your feature importance dictionary (replace with your actual results)
feature_importance = {
    'Orbit Mean Density (kg/m^3)_x_detrended': 0.4285,
    'Orbit Mean Density (kg/m^3)_x_lag_39': 0.3424,
    'Orbit Mean Density (kg/m^3)_x_lag_41': 0.0565,
    'xrsb_flux_x': 0.0214,
    'xrsa_flux_x': 0.0137,
    'Kp_index_rolling_mean_72h': 0.0103,
    'pc_index': 0.0103,
    'Proton_flux_>2_Mev': 0.0071,
    'Kp_index_lag_114h': 0.0062,
    'Kp_index_lag_54h': 0.0061,
    'Proton_flux_>60_Mev': 0.0057,
    'xrsb_flux_y': 0.0056,
    'Proton_flux_>30_Mev': 0.0053,
    'Proton_flux_>1_Mev': 0.0051,
    'xrsa_flux_y': 0.0048,
    'Kp_index_rolling_std_72h': 0.0046,
    'Orbit Mean Density (kg/m^3)_x_lag_1': 0.0043,
    'R_Sunspot_No': 0.0042,
    'AU_index_nT': 0.0035,
    'AL_index_nT': 0.0030,
    # ... (rest of your features and importances)
}

# Select the top 10 most important features
top_n = 10
selected_df = create_and_drop_features(combined_all_x_c_full.copy(), feature_importance, top_n)
print(f"\nDataFrame with the top {top_n} features:")
print(selected_df.head())

# Select all features that have a non-zero importance (example)
selected_df_nonzero = create_and_drop_features(combined_all_x_c_full.copy(), feature_importance)
print("\nDataFrame with all features having non-zero importance:")
print(selected_df_nonzero.head())

"""

def create_eng_chosen_feats(df, dict_selected_features,lags,rolls):
    #dict_selected_features=dict ,> keys feature names , values : reuired engineeing lag, windown,integrall ....
    df_eng = pd.dataFrame([])
    for feat_name in df.columns:
      for req_feats in dict_selected_features[feat_name]:
        if req_feats =="lag":
            for lag in lags:
              lag_column_name = f'{feat_name}_lag_{lag}'
              df_eng[lag_column_name] = df_eng[feat_name].shift(lag)
              df_eng.fillna(0,inplace=True) #bfill().ffill()  # Fill NaN values with 0
        elif req_feats =="roll_mean":
            for roll in rolls:
              roll_column_name = f'{feat_name}_roll_mean_{roll}'
              df_eng[roll_column_name]=df_eng[feat_name].rolling(window=roll).mean()
              df_eng.fillna(0,inplace=True) #bfill().ffill()  # Fill NaN values with 0

        elif req_feats=="roll_std":
              #df_engineered[f'{kp_col}_rolling_std_{window*3}h'] = df_engineered[kp_col].rolling(window=window, min_periods=1).std()
              for roll in rolls :

                roll_column_name = f'{feat_name}_roll_std_{roll}'
                df_eng[roll_column_name]=df_eng[feat_name].rolling(window=roll).std()
                df_eng.fillna(0,inplace=True) #bfill().ffill()  # Fill NaN values with 0


        else:
          # just choose featu
          pass


    return df_eng


"""




def create_eng_chosen_feats(df, dict_selected_features, lags, rolls):
    """
    Creates engineered features (lags, rolling statistics) for a chosen subset
    of features from the input DataFrame based on the provided dictionary.

    Args:
        df (pd.DataFrame): The input DataFrame containing the original features.
        dict_selected_features (dict): A dictionary where keys are feature names
                                       (matching columns in df) and values are
                                       a list of required engineering features
                                       (e.g., ["lag"], ["roll_mean"], ["lag", "roll_std"]).
        lags (list): A list of integer values representing the lags to create.
        rolls (list): A list of integer values representing the window sizes for
                     rolling statistics (mean and std).

    Returns:
        pd.DataFrame: A new DataFrame containing the engineered features for the
                      selected features.
    """
    df_eng = pd.DataFrame([])
    for feat_name in df.columns:
        if feat_name in dict_selected_features:
            for req_feat in dict_selected_features[feat_name]:
                if req_feat == "lag":
                    for lag in lags:
                        lag_column_name = f'{feat_name}_lag_{lag}'
                        df_eng[lag_column_name] = df[feat_name].shift(lag)
                        df_eng.fillna(0, inplace=True)  # Fill NaN values with 0
                elif req_feat == "roll_mean":
                    for roll in rolls:
                        roll_column_name = f'{feat_name}_roll_mean_{roll}'
                        df_eng[roll_column_name] = df[feat_name].rolling(window=roll).mean()
                        df_eng.fillna(0, inplace=True)  # Fill NaN values with 0
                elif req_feat == "roll_std":
                    for roll in rolls:
                        roll_column_name = f'{feat_name}_roll_std_{roll}'
                        df_eng[roll_column_name] = df[feat_name].rolling(window=roll).std()
                        df_eng.fillna(0, inplace=True)  # Fill NaN values with 0
                # If req_feat is not "lag", "roll_mean", or "roll_std", we assume
                # the user wants to keep the original feature.
                elif req_feat == "original":
                    df_eng[feat_name] = df[feat_name]

    return df_eng
"""
data = combined_all_x_c_full.copy()
df_original = pd.DataFrame(data)

selected_features_config = {
    'Kp_index': ['lag', 'roll_mean',],
    'Orbit Mean Density (kg/m^3)_x': ['roll_std', 'original'],
    'xrsb_flux_x': ['original']

    'xrsa_flux_x': ['original']
     'pc_index':['original']
     'Proton_flux_>2_Mev':['original']
     'Proton_flux_>60_Mev':['original']
     'Proton_flux_>30_Mev':['original']
     'R_Sunspot_No':['original']
     'AU_index_nT':['original']
     'Al_index_nT':['original']
}

lags_to_create = [1, 39,41]
rolling_windows = [72]

df_engineered = create_eng_chosen_feats(df_original.copy(), selected_features_config, lags_to_create, rolling_windows)
print(df_engineered)
"""

def prep_data(combined_all_x,combined_all_y,seq=6):
  X, y = [], []

  for i in range(len(combined_all_x) - seq):
    X.append(combined_all_x.iloc[i:i + seq].values)
    y.append(combined_all_y.iloc[i + seq])
    X, y = np.array(X), np.array(y)
    return X,y


X,y=prep_data(combined_all_x_c_full,combined_all_y,seq=3)

print(X.shape)
print(y.shape)

import torch
import torch
import torch.nn as nn
from torch import Tensor
"""

class TemporalSpatialTransformer(nn.Module):
    def __init__(self, input_dim, sequence_length, num_heads, num_layers, hidden_dim):
        super().__init__()
        self.embedding = nn.Linear(input_dim, hidden_dim)  # Project input_dim to hidden_dim
        self.transformer = nn.Transformer(
            d_model=hidden_dim,
            nhead=num_heads,
            num_encoder_layers=num_layers,
            num_decoder_layers=num_layers,
            dim_feedforward=hidden_dim * 4,
            batch_first=True,
        )
        self.fc = nn.Linear(hidden_dim, 1)  # Final layer to predict a single value

    def forward(self, x):
        # x shape: (batch_size, sequence_length, input_dim)
        x = self.embedding(x)  # Shape: (batch_size, sequence_length, hidden_dim)
        x = self.transformer(x, x)  # Shape: (batch_size, sequence_length, hidden_dim)
        x = x.mean(dim=1)  # Pool across the sequence dimension
        return self.fc(x)  # Shape: (batch_size, 1)


model = TemporalSpatialTransformer(
    input_dim=63,           # Matches the feature dimension
    sequence_length=4,     # Matches the sequence length
    num_heads=4,            # Ensure `embed_dim` is divisible by `num_heads`
    num_layers=2,
    hidden_dim=256          # Embed dimension, ensure it's divisible by `num_heads`
)
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
def scale_independent_features(df):
    scalers = {}
    scaled_df = df.copy()
    for column in df.columns:
        scaler = MinMaxScaler()
        scaled_df[column] = scaler.fit_transform(df[[column]])
        scalers[column] = scaler
    return scaled_df, scalers

def create_rolling_window_sequences(scaled_df, data_y, history_length, forecast_length, feature_names):
    X, y = [], []
    for i in range(len(scaled_df) - history_length - forecast_length + 1):
        X.append(scaled_df.iloc[i:(i + history_length)].values)
        y.append(data_y.iloc[i + history_length:i + history_length + forecast_length].values)
    return np.array(X), np.array(y), feature_names, list(scaled_df.columns)

# --- Load Your Data ---
data_points = 1000
features = 95
forecast = 3
history = 60
feature_names = combined_all_x_c_full.columns.tolist()

# Scale each feature independently
scaled_df, scalers = scale_independent_features(combined_all_x_c_full)

# Create rolling window sequences using the independently scaled data
X, y, original_feature_names, scaled_feature_names = create_rolling_window_sequences(
    scaled_df, combined_all_y, history, forecast, feature_names
)


# Flatten X as before
n_samples, seq_len, n_features = X.shape
X_flat = X.reshape(n_samples * seq_len, n_features)

# Flatten y to align with the number of sequences (take the first forecast step as the target)
y_flat = y[:, 0].reshape(n_samples * 1, 1) # Shape will be (n_sequences, 1) repeated for each time step
y_flat_repeated = np.repeat(y_flat, seq_len, axis=0) # Repeat the target for each time step in the sequence

# Now y_flat_repeated should have the same number of samples as X_flat
print(f"Shape of X_flat: {X_flat.shape}")
print(f"Shape of y_flat_repeated: {y_flat_repeated.shape}")

X_train_flat, X_test_flat, y_train_flat, y_test_flat = train_test_split(
    X_flat, y_flat_repeated, test_size=0.2, random_state=42
)

# --- Train a Random Forest Regressor ---
rf_model = RandomForestRegressor(n_estimators=50, random_state=42, n_jobs=-1)
rf_model.fit(X_train_flat, y_train_flat.ravel())

# ... (rest of your feature importance calculation and visualization)


X
# --- Get Feature Importances ---
importances = rf_model.feature_importances_

# Create a mapping of feature names to their importance scores
feature_importance = dict(zip(feature_names, importances))

# Sort features by importance in descending order
sorted_feature_importance = sorted(feature_importance.items(), key=lambda item: item[1], reverse=True)

# --- Display Most Important Features ---
print("--- Most Important Features (based on Random Forest) ---")

for feature, importance in sorted_feature_importance:
    print(f"Feature: {feature}, Importance: {importance:.4f}")

# --- Optional: Visualize Feature Importances ---
import matplotlib.pyplot as plt

top_n = 20 # Display the top N important features
top_features = sorted_feature_importance[:top_n]
feature_names_top = [f[0] for f in top_features]
importance_scores_top = [f[1] for f in top_features]

plt.figure(figsize=(12, 6))
plt.bar(feature_names_top, importance_scores_top)
plt.xlabel("Feature")
plt.ylabel("Importance Score")
plt.title(f"Top {top_n} Feature Importances (Random Forest)")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
import math
import numpy as np
from sklearn.preprocessing import MinMaxScaler

sequence_length = 60
history_length = 60

input_dim = 95
sequence_length = sequence_length
num_heads = 8
num_layers = 4
hidden_dim = 256
forecast_length = 3
dropout = 0.4
use_last_timestep = True

def create_rolling_window_sequences(data, target_column, history_length=history_length, forecast_length=3):
    X, y, timestamps = [], [], []
    n_samples = len(data)
    features = data.values
    targets = target_column.values
    time_index = data.index

    for i in range(n_samples - history_length - forecast_length + 1):
        X.append(features[i : i + history_length])
        y.append(targets[i + history_length : i + history_length + forecast_length])
        timestamps.append(time_index[i + history_length - 1])  # Timestamp at the end of the historical window

    return np.array(X), np.array(y), np.array(timestamps)

def prep_data_for_rolling_window(combined_all_x_c_full, combined_all_y, history_length=history_length, forecast_length=3):
    X, y, timestamps = create_rolling_window_sequences(combined_all_x_c_full, combined_all_y, history_length, forecast_length)

    # Scale the input features
    n_samples, seq_len, n_features = X.shape
    X_reshaped = X.reshape(-1, n_features)
    scaler = MinMaxScaler()
    X_scaled_reshaped = scaler.fit_transform(X_reshaped)
    X_scaled = X_scaled_reshaped.reshape(n_samples, seq_len, n_features)

    return X_scaled, y, scaler, timestamps

# Assuming combined_all_x_c_full and combined_all_y are defined DataFrames
# Example DataFrames (replace with your actual data)
data_points = 100
features = 95
forecast = 3
history = 60


X_train, y_train, scaler_rolling, train_timestamps = prep_data_for_rolling_window(combined_all_x_c_full, combined_all_y, history_length=history_length, forecast_length=forecast_length)

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, dropout, max_len=5000):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe) # Shape: (max_len, d_model)

    def forward(self, x):
        # x shape: (batch_size, seq_len, d_model)
        seq_len = x.size(1)
        pe_for_input = self.pe[:seq_len, :].unsqueeze(0) # Shape: (1, seq_len, d_model)
        x = x + pe_for_input
        return self.dropout(x)

class ImprovedTemporalSpatialTransformer(nn.Module):
    def __init__(self, input_dim, sequence_length, num_heads, num_layers, hidden_dim, forecast_length, dropout=0.1, use_last_timestep=False):
        super().__init__()
        self.embedding = nn.Linear(input_dim, hidden_dim)
        self.pos_encoder = PositionalEncoding(hidden_dim, dropout, max_len=sequence_length)
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=num_heads, dim_feedforward=hidden_dim * 4, dropout=dropout, batch_first=True),
            num_layers=num_layers
        )
        self.use_last_timestep = use_last_timestep
        if use_last_timestep:
            self.fc = nn.Linear(hidden_dim, forecast_length)
        else:
            self.fc = nn.Linear(hidden_dim, forecast_length) # Predicting from the pooled sequence

    def forward(self, src):
        src = self.embedding(src)
        src = self.pos_encoder(src)
        encoder_output = self.transformer_encoder(src) # Shape: (batch_size, sequence_length, hidden_dim)

        if self.use_last_timestep:
            # Take the output of the last time step
            last_output = encoder_output[:, -1, :] # Shape: (batch_size, hidden_dim)
            return self.fc(last_output) # Shape: (batch_size, forecast_length)
        else:
            # Take the mean across the sequence dimension
            pooled_output = encoder_output.mean(dim=1) # Shape: (batch_size, hidden_dim)
            return self.fc(pooled_output) # Shape: (batch_size, forecast_length)

improved_model = ImprovedTemporalSpatialTransformer(
    input_dim=input_dim,
    sequence_length=sequence_length,
    num_heads=num_heads,
    num_layers=num_layers,
    hidden_dim=hidden_dim,
    forecast_length=forecast_length,
    dropout=dropout,
    use_last_timestep=use_last_timestep
)
print(improved_model)

"""
++++++++++++++++++++++++++++++++++++++++++++++++++++++

"""

from torch.utils.data import DataLoader, TensorDataset
from torch.optim import Adam


# Convert data to PyTorch tensors
X_tensor = torch.tensor(X_train, dtype=torch.float32)
y_tensor = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)

print(X_tensor.shape)
print(y_tensor.shape)

dataset = TensorDataset(X_tensor, y_tensor)

dataloader = DataLoader(dataset, batch_size=64, shuffle=True)

# Initialize model, loss, and optimizer
criterion = nn.MSELoss()
optimizer = Adam(improved_model.parameters(), lr=0.0005)

# Training loop
for epoch in range(10):  # Adjust epochs as needed
    for batch_X, batch_y in dataloader:
        optimizer.zero_grad()
        predictions = improved_model(batch_X)

        loss = criterion(predictions, batch_y)

        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch + 1}, Loss: {loss.item():.4f}")

len(combined_all_x_c_full)

import torch
import pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

def evaluate_future_prediction(full_df, model, target_series, window_size=history_length, forecast_length=3, scaler=None, device='cpu'):
    model.eval()
    model.to(device)

    print(f"Length of full_df received: {len(full_df)}")
    print(f"Length of target_series received: {len(target_series)}")

    full_df = full_df.sort_index()
    target_series = target_series.sort_index()
    print("target_series",target_series)
    # Check if we have enough data for evaluation
    if len(full_df) < window_size + forecast_length:
        print(f"Error: full_df is too short for evaluation with window_size={window_size} and forecast_length={forecast_length}.")
        return None

    # Extract the last 'window_size + forecast_length' rows for evaluation
    evaluation_df = full_df.iloc[-(window_size + forecast_length):]
    evaluation_target = target_series.iloc[-(window_size + forecast_length):]

    # Prepare the input window (last 'window_size' rows of features)
    last_window = evaluation_df.iloc[:-forecast_length].values

    if scaler:
        scaled_window = scaler.transform(last_window)
    else:
        scaled_window = last_window

    input_tensor = torch.tensor(scaled_window, dtype=torch.float32).unsqueeze(0).to(device)

    # Make the prediction for the next 'forecast_length' steps
    with torch.no_grad():
        future_predictions = model(input_tensor).cpu().numpy()

    # Get the actual target values for the 'forecast_length' days after the window
    actual_values = evaluation_target.iloc[-forecast_length:].values.reshape(1, -1)

    # Get the timestamps for the predicted days
    evaluation_timestamps = evaluation_df.index[-forecast_length:]

    # Create a DataFrame for comparison
    results_df = pd.DataFrame({
        'Timestamp': evaluation_timestamps,
        'Actual': actual_values.flatten(),
        'Predicted': future_predictions.flatten()
    }).set_index('Timestamp')

    mse = mean_squared_error(actual_values, future_predictions)
    mae = mean_absolute_error(actual_values, future_predictions)

    print(f"Evaluation Metrics (Last {forecast_length} days):")
    print(f"Mean Squared Error (MSE): {mse:.4f}")
    print(f"Mean Absolute Error (MAE): {mae:.4f}")

    return results_df

"""
# Example Usage (same as before)
evaluation_results = evaluate_future_prediction(
    combined_all_x_c_full,
    improved_model,
    target_series=combined_all_y,
    window_size=history_length,
    forecast_length=3,
    scaler=scaler_rolling,
    device='cuda' if torch.cuda.is_available() else 'cpu'
)

if evaluation_results is not None:
    print("\nPrediction vs. Actual (Last 3 Days):")
    print(evaluation_results)
"""

import torch
import pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

def rolling_window_evaluation(full_df, model, target_series, window_size, forecast_length, scaler=None, device='cpu', num_predictions=5):
    """
    Performs rolling window evaluation by iteratively removing the last
    'forecast_length' elements, predicting them, and comparing with actual values.

    Args:
        full_df (pd.DataFrame): The complete preprocessed DataFrame with 'Timestamp' as index.
        model (torch.nn.Module): The trained PyTorch model.
        target_series (pd.Series): The complete target variable Series with 'Timestamp' as index.
        window_size (int): The size of the historical input window.
        forecast_length (int): The number of future steps the model predicts.
        scaler (MinMaxScaler, optional): The scaler used for the features during training.
        device (str): The device to use for the model ('cpu' or 'cuda').
        num_predictions (int): The number of rolling predictions to perform from the end of the data.

    Returns:
        pd.DataFrame: A DataFrame containing the actual and predicted values for all
                      performed predictions, along with overall evaluation metrics.
    """
    model.eval()
    model.to(device)

    print(f"Length of full_df received: {len(full_df)}")
    print(f"Length of target_series received: {len(target_series)}")

    full_df = full_df.sort_index()
    target_series = target_series.sort_index()

    results = []
    all_actual = []
    all_predicted = []
    all_timestamps = []

    for i in range(num_predictions):
        # Calculate the starting index for the evaluation window
        eval_end_index = len(full_df) - (i * forecast_length)
        eval_start_index = eval_end_index - (window_size + forecast_length)

        if eval_start_index < 0:
            print(f"Warning: Not enough data for {num_predictions} rolling predictions with current window and forecast length.")
            break

        evaluation_df = full_df.iloc[eval_start_index:eval_end_index]
        evaluation_target = target_series.iloc[eval_start_index:eval_end_index]

        # Prepare the input window
        last_window = evaluation_df.iloc[:-forecast_length].values

        if scaler:
            scaled_window = scaler.transform(last_window)
        else:
            scaled_window = last_window

        input_tensor = torch.tensor(scaled_window, dtype=torch.float32).unsqueeze(0).to(device)

        # Make the prediction
        with torch.no_grad():
            future_predictions = model(input_tensor).cpu().numpy()

        # Get the actual target values
        actual_values = evaluation_target.iloc[-forecast_length:].values.reshape(1, -1)
        timestamps = evaluation_df.index[-forecast_length:]

        results.append(pd.DataFrame({
            'Timestamp': timestamps,
            'Actual': actual_values.flatten(),
            'Predicted': future_predictions.flatten()
        }).set_index('Timestamp'))

        all_actual.extend(actual_values.flatten())
        all_predicted.extend(future_predictions.flatten())
        all_timestamps.extend(timestamps)

    if not results:
        return None

    final_results_df = pd.concat(results)

    overall_mse = mean_squared_error(all_actual, all_predicted)
    overall_mae = mean_absolute_error(all_actual, all_predicted)

    print("\nRolling Window Evaluation Results:")
    print(final_results_df)
    print(f"\nOverall Mean Squared Error (MSE) across {len(all_actual)} predictions: {overall_mse:.4f}")
    print(f"Overall Mean Absolute Error (MAE) across {len(all_actual)} predictions: {overall_mae:.4f}")

    return final_results_df
# Example Usage (assuming you have your full preprocessed DataFrame 'combined_all_x_c_full',
# target Series 'combined_all_y', trained 'improved_model', and 'scaler'):
history_length = 60  # Or your defined window size
num_predictions_to_evaluate = 6  # Number of times to predict from the end

rolling_results_df = rolling_window_evaluation(
    combined_all_x_c_full.copy(),
    improved_model,
    combined_all_y.copy(),
    window_size=history_length,
    forecast_length=3,
    scaler=scaler_rolling,
    device='cuda' if torch.cuda.is_available() else 'cpu',
    num_predictions=num_predictions_to_evaluate
)

if rolling_results_df is not None:
    print("\nCombined Rolling Prediction Results:")
    print(rolling_results_df)

!pip install Darts

!pip install --upgrade transformers

import torch
import torch.nn as nn
import math
from huggingface_hub import hf_hub_download
import torch
from transformers import TimeSeriesTransformerForPrediction
import torch
import torch.nn as nn
import math
from transformers import TimeSeriesTransformerForPrediction
from huggingface_hub import hf_hub_download

import torch
import torch.nn as nn
import math
from transformers import AutoModelForCausalLM

# Your custom Transformer definition (as before)
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, dropout, max_len=5000):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe)
    def forward(self, x):
        seq_len = x.size(1)
        pe_for_input = self.pe[:seq_len, :].unsqueeze(0)
        x = x + pe_for_input
        return self.dropout(x)

class ImprovedTemporalSpatialTransformerHF(nn.Module):
    def __init__(self, input_dim, sequence_length, num_heads, num_layers, hidden_dim, forecast_length, dropout=0.1, use_last_timestep=False, pretrained_model=None):
        super().__init__()
        self.pretrained_model = pretrained_model if pretrained_model else nn.TransformerEncoder(
            nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=num_heads, dim_feedforward=hidden_dim * 4, dropout=dropout, batch_first=True),
            num_layers=num_layers

        )

        self.embedding = nn.Linear(input_dim, hidden_dim)
        self.pos_encoder = PositionalEncoding(hidden_dim, dropout, max_len=sequence_length)
        self.use_last_timestep = use_last_timestep
        self.fc = nn.Linear(hidden_dim, forecast_length)
        self.projection_layer = nn.Linear( hidden_dim, hidden_dim) # Project logits



    def forward(self, src):
        embedded = self.embedding(src)
        positioned = self.pos_encoder(embedded)
        pretrained_output = self.pretrained_model(inputs_embeds=positioned)
        print("Type of pretrained_output:", type(pretrained_output))
        if hasattr(pretrained_output, 'keys'):
          print("Keys of pretrained_output:", pretrained_output.keys())
        else:
          print("Attributes of pretrained_output:", dir(pretrained_output))
        logits = pretrained_output.logits # Shape: (batch_size, sequence_length, vocab_size)
        # Process the logits - you might need to understand how the vocab_size relates to your data
        # A simple approach is to project it to your hidden_dim
        encoder_output = self.projection_layer(logits) # Shape: (batch_size, sequence_length, hidden_dim)

        if self.use_last_timestep:
            last_output = encoder_output[:, -1, :]
            return self.fc(last_output)
        else:
            pooled_output = encoder_output.mean(dim=1)
            return self.fc(pooled_output)
# --- Load the pre-trained Timer model ---
pretrained_model_name = 'thuml/timer-base-84m'
try:
    pretrained_timer_model = AutoModelForCausalLM.from_pretrained(pretrained_model_name, trust_remote_code=True)
    print(f"Pre-trained Timer model '{pretrained_model_name}' loaded successfully.")
except Exception as e:
    print(f"Error loading pre-trained Timer model: {e}")
    pretrained_timer_model = None

# --- Hyperparameters for your custom model (try to match Timer's if possible) ---
input_dim = 95
sequence_length = 60
num_heads = 8  # Adjust based on Timer's config
num_layers = 6  # Adjust based on Timer's config
hidden_dim = 1024 # Adjust based on Timer's config
forecast_length = 3
dropout = 0.1

# --- Instantiate your custom model, passing the pretrained Timer model ---
your_model_hf = ImprovedTemporalSpatialTransformerHF(
    input_dim, sequence_length, num_heads, num_layers, hidden_dim, forecast_length, dropout, pretrained_model=pretrained_timer_model.model if pretrained_timer_model else None
)

print("\nYour Custom Model Instantiated.")

# --- Function to copy weights from Timer's encoder ---
def copy_weights_from_timer(pretrained_model, your_encoder):
    if pretrained_model is None:
        print("Pre-trained Timer model not loaded, skipping weight copy.")
        return

    pretrained_encoder_layers = [module for name, module in pretrained_model.named_modules() if "transformer.h." in name]
    your_encoder_layers = [module for name, module in your_encoder.named_modules() if "encoder.layer" in name]

    num_layers_to_copy = min(len(pretrained_encoder_layers), len(your_encoder_layers))

    with torch.no_grad():
        for i in range(num_layers_to_copy):
            pretrained_layer = pretrained_encoder_layers[i].attn
            your_layer = your_encoder_layers[i].self_attn # Assuming your attention layer is named 'self_attn'
            try:
                # Timer uses a specific attention mechanism, direct copy might not be perfect
                # You might need to inspect the layers and copy individual weight matrices
                your_layer.in_proj_weight.copy_(pretrained_layer.c_attn.weight[:, :your_layer.embed_dim * 3])
                your_layer.in_proj_bias.copy_(pretrained_layer.c_attn.bias[:your_layer.embed_dim * 3])
                your_layer.out_proj.weight.copy_(pretrained_layer.c_proj.weight)
                your_layer.out_proj.bias.copy_(pretrained_layer.c_proj.bias)
                print(f"Copied attention weights from Timer layer {i+1} to your encoder layer {i+1}")
            except RuntimeError as e:
                print(f"Shape mismatch in attention at layer {i+1}: {e}")

            pretrained_mlp_layer = pretrained_encoder_layers[i].mlp
            your_mlp_layer = your_encoder_layers[i].linear1 # Assuming your first MLP layer is 'linear1'
            try:
                your_mlp_layer.weight.copy_(pretrained_mlp_layer.c_fc.weight)
                your_mlp_layer.bias.copy_(pretrained_mlp_layer.c_fc.bias)
                print(f"Copied MLP1 weights from Timer layer {i+1} to your encoder layer {i+1}")
            except RuntimeError as e:
                print(f"Shape mismatch in MLP1 at layer {i+1}: {e}")

            your_mlp_out_layer = your_encoder_layers[i].linear2 # Assuming your second MLP layer is 'linear2'
            try:
                your_mlp_out_layer.weight.copy_(pretrained_mlp_layer.c_proj.weight)
                your_mlp_out_layer.bias.copy_(pretrained_mlp_layer.c_proj.bias)
                print(f"Copied MLP2 weights from Timer layer {i+1} to your encoder layer {i+1}")
            except RuntimeError as e:
                print(f"Shape mismatch in MLP2 at layer {i+1}: {e}")

            # Copy LayerNorm weights if present and named similarly
            if hasattr(pretrained_encoder_layers[i], 'ln_1') and hasattr(your_encoder_layers[i], 'norm1'):
                try:
                    your_encoder_layers[i].norm1.weight.copy_(pretrained_encoder_layers[i].ln_1.weight)
                    your_encoder_layers[i].norm1.bias.copy_(pretrained_encoder_layers[i].ln_1.bias)
                    print(f"Copied LayerNorm1 weights from Timer layer {i+1}")
                except RuntimeError as e:
                    print(f"Shape mismatch in LayerNorm1 at layer {i+1}: {e}")

            if hasattr(pretrained_encoder_layers[i], 'ln_2') and hasattr(your_encoder_layers[i], 'norm2'):
                try:
                    your_encoder_layers[i].norm2.weight.copy_(pretrained_encoder_layers[i].ln_2.weight)
                    your_encoder_layers[i].norm2.bias.copy_(pretrained_encoder_layers[i].ln_2.bias)
                    print(f"Copied LayerNorm2 weights from Timer layer {i+1}")
                except RuntimeError as e:
                    print(f"Shape mismatch in LayerNorm2 at layer {i+1}: {e}")

# --- Copy the weights ---
if pretrained_timer_model:
    copy_weights_from_timer(pretrained_timer_model, your_model_hf.pretrained_model)

# --- You would now train 'your_model_hf' on your orbital density data. ---
# --- Remember to handle the input embedding and the final prediction layer. ---

import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import torch.nn as nn
from torch.optim import Adam

# --- Hyperparameters (consistent with your original setup) ---
sequence_length = 60
history_length = 60  # Alias for sequence_length
input_dim = 95
forecast_length = 3
batch_size = 32 # Define batch size here as well if needed

# --- Define a Custom Dataset for your DataFrames ---
class OrbitalDensityDatasetFromDF(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return {"src": self.X[idx], "targets": self.y[idx]}

# --- Function to Create Rolling Window Sequences from DataFrames ---
def create_rolling_window_sequences_from_df(data_df, target_df, history_length=history_length, forecast_length=forecast_length):
    X, y = [], []
    n_samples = len(data_df)
    features = data_df.values
    targets = target_df.values

    for i in range(n_samples - history_length - forecast_length + 1):
        X.append(features[i : i + history_length])
        y.append(targets[i + history_length : i + history_length + forecast_length])

    return np.array(X), np.array(y)

# --- Prepare Data for Rolling Window from DataFrames ---
def prep_data_for_rolling_window_df(combined_all_x_c_full, combined_all_y, history_length=history_length, forecast_length=forecast_length):
    X, y = create_rolling_window_sequences_from_df(combined_all_x_c_full, combined_all_y, history_length, forecast_length)

    # Scale the input features
    n_samples, seq_len, n_features = X.shape
    X_reshaped = X.reshape(-1, n_features)
    scaler = MinMaxScaler()
    X_scaled_reshaped = scaler.fit_transform(X_reshaped)
    X_scaled = X_scaled_reshaped.reshape(n_samples, seq_len, n_features)

    return X_scaled, y, scaler

# --- Load and Prepare Your Data ---
# Assuming combined_all_x_c_full and combined_all_y are your DataFrames
# Replace these with your actual loading mechanism if needed
# Example DataFrames (replace with your actual data)
data_points = 1000
features = 95
forecast = 3
history = 60
combined_all_x_c_full = pd.DataFrame(np.random.rand(data_points, features))
combined_all_y = pd.DataFrame(np.random.rand(data_points, 1)) # Assuming single target variable for now

X_train_scaled, y_train, scaler = prep_data_for_rolling_window_df(combined_all_x_c_full, combined_all_y, history_length=history_length, forecast_length=forecast_length)

# --- Create Training Dataset and DataLoader ---
train_dataset = OrbitalDensityDatasetFromDF(X_train_scaled, y_train)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# --- Instantiate your model (assuming you've defined either ImprovedTemporalSpatialTransformer or ImprovedTemporalSpatialTransformerHF) ---
# Make sure this instantiation happens in the global scope, before the if __name__ == "__main__": block
# Example instantiation (replace with your actual model instantiation)



# --- Training Loop ---
if __name__ == "__main__":
    your_model_hf.train()
    criterion = nn.MSELoss()
    optimizer = Adam(your_model_hf.parameters(), lr=0.0005)
    num_epochs = 10  # Adjust epochs as needed

    for epoch in range(num_epochs):
        for batch in train_loader:
            src_batch = batch["src"]
            targets_batch = batch["targets"]
            print("Source Batch Shape:", src_batch.shape)
            print("Targets Batch Shape:", targets_batch.shape)

            optimizer.zero_grad()
            predictions = your_model_hf.forward(src_batch)

            loss = criterion(predictions, targets_batch)

            loss.backward()
            optimizer.step()
        print(f"Epoch {epoch + 1}, Loss: {loss.item():.4f}")

import pandas as pd
import os
import re
from datetime import datetime

def find_and_read_matching_files_from_dict(date_dict, data_directory):
    """
    Takes a dictionary containing start and end timestamps, then searches a
    directory for CSV files whose timestamps fall within this range.

    Args:
        date_dict (dict): A dictionary with 'start_timestamp' and 'end_timestamp'
                           keys. The values should be Pandas Timestamp objects
                           or strings that can be converted to datetime objects.
                           Example: {'start_timestamp': pd.Timestamp('2000-08-02 04:50:33'),
                                     'end_timestamp': pd.Timestamp('2000-12-04 18:00:35')}
        data_directory (str): Path to the directory containing the data files
                                (format: champ_-XXXXX-YYYYMMDD_to_YYYYMMDD.csv).

    Returns:
        dict: A dictionary where keys are the file paths of the opened CSV files
              and values are the Pandas DataFrames read from those files.
              Returns an empty dictionary if no matching files are found or
              if there's an error with the provided dates.
    """
    try:
        start_date = pd.to_datetime(date_dict['start_timestamp'])
        end_date = pd.to_datetime(date_dict['end_timestamp'])
    except KeyError:
        print("Error: The input dictionary must contain 'start_timestamp' and 'end_timestamp' keys.")
        return {}
    except ValueError:
        print("Error: Could not parse 'start_timestamp' or 'end_timestamp' into datetime objects.")
        return {}

    matching_files = {}
    for filename in os.listdir(data_directory):
        if filename.endswith(".csv") and re.match(r"champ_-\d{5}-\d{8}_to_\d{8}\.csv", filename):
            try:
                file_start_str = re.search(r"-(\d{8})_to_", filename).group(1)
                file_end_str = re.search(r"_to_(\d{8})\.csv", filename).group(1)

                file_start_date = datetime.strptime(file_start_str, "%Y%m%d")
                file_end_date = datetime.strptime(file_end_str, "%Y%m%d")

                if (file_start_date <= end_date and file_end_date >= start_date):
                    filepath = os.path.join(data_directory, filename)
                    try:
                        matching_files[filepath] = pd.read_csv(filepath)
                        print(f"Successfully read file: {filename}")
                    except Exception as e:
                        print(f"Error reading data file '{filename}': {e}")
            except AttributeError:
                print(f"Warning: Could not parse timestamp from filename '{filename}'. Skipping.")
            except ValueError:
                print(f"Warning: Invalid date format in filename '{filename}'. Skipping.")

    if not matching_files:
        print("No matching data files found within the specified date range.")

    return matching_files

if __name__ == '__main__':
    # Example Usage:
    data_dir = '/content/drive/MyDrive/data/champ'  # <--- PLACEHOLDER FOR YOUR REAL DIRECTORY PATH

    # Define the dictionary with start and end timestamps
    date_range = {
        'input_slice': (0, 60),
        'target_slice': (60, 63),
        'start_timestamp': pd.Timestamp('2000-08-05 00:00:00'),
        'end_timestamp': pd.Timestamp('2000-10-25 23:59:59')
    }


    matching_data = find_and_read_matching_files_from_dict(date_range, data_dir)

    if matching_data:
        print("\nMatching data files read:")
        for filepath, df in matching_data.items():
            print(f"- {filepath}:")
            print(df.head())





import pandas as pd
import os
import re
from datetime import datetime

def find_and_read_matching_files_multi_source(date_dict, data_directories):
    """
    Takes a dictionary containing start and end timestamps, then searches
    multiple directories for CSV files (prefixed with 'champ-', 'goes-', or 'omni-')
    whose timestamps fall within this range.

    For 'champ' files, it uses the specific 'champ_-\d{5}-\d{8}_to_\d{8}\.csv' pattern.
    For 'goes' and 'omni' files, it uses the pattern to extract date ranges.

    Args:
        date_dict (dict): A dictionary with 'start_timestamp' and 'end_timestamp'
                           keys. The values should be Pandas Timestamp objects
                           or strings that can be converted to datetime objects.
                           Example: {'start_timestamp': pd.Timestamp('2000-08-02 04:50:33'),
                                     'end_timestamp': pd.Timestamp('2000-12-04 18:00:35')}
        data_directories (dict): A dictionary where keys are source names
                                   ('champ', 'goes', 'omni') and values are the
                                   corresponding directory paths.
                                   Example: {'champ': '/path/to/champ_data',
                                             'goes': '/path/to/goes_data',
                                             'omni': '/path/to/omni_data'}

    Returns:
        dict: A dictionary where keys are the file paths of the opened CSV files
              and values are the Pandas DataFrames read from those files.
              The keys will be prefixed with the source name to avoid collisions.
              Returns an empty dictionary if no matching files are found or
              if there's an error with the provided dates or directories.
    """
    try:
        start_date = pd.to_datetime(date_dict['start_timestamp'])
        end_date = pd.to_datetime(date_dict['end_timestamp'])
    except KeyError:
        print("Error: The input dictionary must contain 'start_timestamp' and 'end_timestamp' keys.")
        return {}
    except ValueError:
        print("Error: Could not parse 'start_timestamp' or 'end_timestamp' into datetime objects.")
        return {}

    matching_files = {}
    valid_sources = ['champ', 'goes', 'omni']

    for source, data_directory in data_directories.items():
        if source not in valid_sources:
            print(f"Warning: Invalid source name '{source}'. Skipping directory.")
            continue
        if not os.path.isdir(data_directory):
            print(f"Warning: Directory not found: {data_directory}")
            continue

        for filename in os.listdir(data_directory):
            if filename.endswith(".csv") and filename.startswith(f"{source}-"):
                try:
                    file_start_date = None
                    file_end_date = None
                    match = re.search(r"-(\d{8})_to_(\d{8})\.csv", filename)

                    if match:
                        file_start_str, file_end_str = match.groups()
                        file_start_date = datetime.strptime(file_start_str, "%Y%m%d").date()
                        file_end_date = datetime.strptime(file_end_str, "%Y%m%d").date()

                        print('champ')
                        if re.match(r"champ_-\d{5}-\d{8}_to_\d{8}\.csv", filename):
                                if (file_start_date <= end_date.date() and file_end_date >= start_date.date()):
                                    filepath = os.path.join(data_directory, filename)
                                    try:
                                        matching_files[f"{source}-{filepath}"] = pd.read_csv(filepath)
                                        print(f"Successfully read file: {filename} from {source}")
                                    except Exception as e:
                                        print(f"Error reading data file '{filename}' from {source}: {e}")
                        if source in ['goes', 'omni']:
                            if (file_start_date <= end_date.date() and file_end_date >= start_date.date()):
                                filepath = os.path.join(data_directory, filename)
                                try:
                                    matching_files[f"{source}-{filepath}"] = pd.read_csv(filepath)
                                    print(f"Successfully read file: {filename} from {source}")
                                except Exception as e:
                                    print(f"Error reading data file '{filename}' from {source}: {e}")
                    else:
                        print(f"Warning: Could not parse date range from filename '{filename}' in {source}. Skipping.")
                except ValueError:
                    print(f"Warning: Invalid date format in filename '{filename}' from {source}. Skipping.")

    if not matching_files:
        print("No matching data files found within the specified date range in the given directories.")

    return matching_files

if __name__ == '__main__':
    # Example Usage:
    data_directories = {
        'champ': '/content/drive/MyDrive/data/champ',  # <--- PLACEHOLDER
        'goes': '/content/drive/MyDrive/data/goes',    # <--- PLACEHOLDER
        'omni': '/content/drive/MyDrive/data/omni'     # <--- PLACEHOLDER
    }

    # Define the dictionary with start and end timestamps
    date_range = {
        'input_slice': (0, 60),
        'target_slice': (60, 63),
        'start_timestamp': pd.Timestamp('2000-08-05 00:00:00'),
        'end_timestamp': pd.Timestamp('2000-10-25 23:59:59')
    }

    matching_data = find_and_read_matching_files_multi_source(date_range, data_directories)
    m2=find_and_read_matching_files_from_dict(date_range, data_directories['champ'])
    matching_data.update(m2)
    if matching_data:
        print("\nMatching data files read:")
        for filepath, df in matching_data.items():
            print(f"- {filepath}:")
            print(df.head())

import pandas as pd
import json
from datetime import datetime
import os

def load_matching_files_from_organization(organization_json_path, date_range):
    """
    Loads CSV files listed in the organization.json whose date ranges overlap
    with the provided date_range.

    Args:
        organization_json_path (str): Path to the organization.json file.
        date_range (dict): A dictionary with 'start_timestamp' and 'end_timestamp'
                           as Pandas Timestamp objects.

    Returns:
        dict: A dictionary where keys are the full file paths of the loaded
              CSV files, and values are the Pandas DataFrames.
    """
    try:
        with open(organization_json_path, 'r') as f:
            organization = json.load(f)
        print(f"Successfully loaded organization.json: {organization}")
    except FileNotFoundError:
        print(f"Error: Organization JSON file not found at '{organization_json_path}'.")
        return {}
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from '{organization_json_path}'.")
        return {}

    start_date_range = date_range['start_timestamp'].date()
    end_date_range = date_range['end_timestamp'].date()
    loaded_files = {}

    for source, files in organization.items():
        if source == 'initial_states':
            continue  # Skip initial states for now

        for file_info in files.values():
            try:
                date_from_str = file_info['date_from']
                date_to_str = file_info['date_to']
                full_path = file_info['full_path']

                file_start_date = datetime.strptime(date_from_str, "%Y-%m-%d").date()
                file_end_date = datetime.strptime(date_to_str, "%Y-%m-%d").date()

                # Check if the file's date range overlaps with the given date range
                if (file_start_date <= end_date_range and file_end_date >= start_date_range):
                    print(f"Attempting to load: {full_path}")
                    try:
                        df = pd.read_csv(full_path)
                        loaded_files[full_path] = df
                        print(f"Successfully loaded: {full_path}")
                    except FileNotFoundError:
                        print(f"Warning: File not found at '{full_path}'. Skipping.")
                    except Exception as e:
                        print(f"Error reading file '{full_path}': {e}")

            except KeyError as e:
                print(f"Warning: Missing key '{e}' in organization data for source '{source}'. Skipping entry.")
            except ValueError:
                print(f"Warning: Invalid date format in organization data for source '{source}'. Skipping entry.")

    if not loaded_files:
        print("No matching files found within the specified date range in the organization data.")

    return loaded_files

if __name__ == '__main__':
    organization_file = '/content/file_organization.json'  # Replace with the actual path if needed
    date_range = {
        'input_slice': (0, 60),
        'target_slice': (60, 63),
        'start_timestamp': pd.Timestamp('2000-08-05 00:00:00'),
        'end_timestamp': pd.Timestamp('2000-10-25 23:59:59')
    }

    loaded_data = load_matching_files_from_organization(organization_file, date_range)

    if loaded_data:
        print("\nLoaded DataFrames:")
        for path, df in loaded_data.items():
            print(f"- {path}:")
            print(df.head())

import os
import re
import json
from datetime import datetime

def organize_files_by_date_and_type(root_dir, output_json="file_organization.json"):
    """
    Pulls files by date (excluding the first date range), classifies them by type,
    and stores their full paths and metadata in a JSON file.

    Args:
        root_dir (str): The root directory to search for files.
        output_json (str): The name of the JSON file to create.
    """
    organization = {
        "champ": {},
        "goes": {},
        "omni": {},
        "initial_states": {}
    }
    file_counts = {
        "champ": 0,
        "goes": 0,
        "omni": 0,
        "initial_states": 0
    }

    # Regex to extract date range from the filename
    date_pattern = re.compile(r"-(\d{8})_to_(\d{8})\.csv") or re.compile(r"champ_-\d{5}-\d{8}_to_\d{8}\.csv") or re.compile(r"grace2-\d{5}-\d{8}_to_\d{8}\.csv")

    for folder in os.listdir(root_dir):
      for filename in os.listdir(os.path.join(root_dir, folder)):
        print(filename)
        match = date_pattern.search(filename)
        if match:
            start_date_str = match.group(1)
            end_date_str = match.group(2)

            try:
                start_date = datetime.strptime(start_date_str, '%Y%m%d').date()
                end_date = datetime.strptime(end_date_str, '%Y%m%d').date()
                first_excluded_date = datetime(2000, 8, 6).date()

                # Exclude files with the first date range (2000-08-06 to 2000-08-06)
                if not (start_date == first_excluded_date and end_date == first_excluded_date):
                    full_path = os.path.join(root_dir+'/'+folder, filename)

                    if filename.startswith("champ"):
                        file_type = "champ"
                    elif filename.startswith("goes"):
                        file_type = "goes"
                    elif filename.startswith("grace2"):
                        file_type = "champ"
                    elif filename.startswith("gr-of1"):
                        file_type = "champ"
                    elif filename.startswith("omni"):
                        file_type = "omni"

                    elif filename.startswith("initial_states"):
                        file_type = "initial_states"
                    else:
                        continue  # Skip files that don't match the prefixes

                    file_counts[file_type] += 1
                    organization[file_type][file_counts[file_type]] = {
                        "date_from": start_date.isoformat(),
                        "date_to": end_date.isoformat(),
                        "full_path": full_path
                    }
            except ValueError:
                print(f"Warning: Could not parse date from filename: {filename}")

    with open(output_json, 'w') as f:
        json.dump(organization, f, indent=4)

    print(f"File organization information saved to: {output_json}")

# Example usage:
if __name__ == "__main__":
    root_directory = "/content/drive/MyDrive/app/dataset/test"  # Replace with the actual path to your files
    organize_files_by_date_and_type(root_directory)