# -*- coding: utf-8 -*-
"""omni_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13XwfXn5nVzJ___3x5vxhd7MdXz50vk28
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import datetime as dt
import datetime
from datetime import datetime

!unzip /content/drive/MyDrive/warmup.zip

!unzip /content/drive/MyDrive/Sat_Density.zip

dfswarma=pd.read_csv("/content/swarma-wu001-20140128_to_20140131.csv",skiprows=0)

dfswarma.head()

dfswarma.tail()

# Function to download NASA OMNI dataset
def download_omni_data(start_year, end_year):
    url = f"https://omniweb.gsfc.nasa.gov/cgi/nx1.cgi?activity=retrieve&res=hour&spacecraft=omni2&start_date={start_year}-01-01&end_date={end_year}-12-31&vars=10,14"
    response = requests.get(url)
    with open("omni_data.txt", "w") as f:
        f.write(response.text)
    print("OMNI data downloaded.")

# Function to preprocess OMNI dataset


# Function to preprocess OMNI dataset
def preprocess_omni_data(filepath):
    #columns = ["Year", "Day", "Hour", "F10.7_flux", "Ap_index"]
    data = pd.read_csv(filepath, skiprows=0)
    print(data.columns)
    # Drop rows with missing or non-numeric values in the critical columns



    # Drop rows with missing or non-numeric values in the critical columns
    data = data.dropna(subset=["YEAR", "DOY", "Hour"]).copy()
    data[["Year", "Day", "Hour"]] = data[["YEAR", "DOY", "Hour"]].apply(pd.to_numeric, errors="coerce")
    #data = data.dropna(subset=["Year", "Day", "Hour"]).copy()
    #data['Datetime'] = [0]*len(data)
    print(data.head())

    #for i,row in data.iterrows():

    #  print(dt.datetime.strptime(f"{int(row[i].Year)}-{int(row[i].Day):03}-{int(row[i].Hour):02}", "%Y-%j-%H"))


    # Combine year, day, and hour into a single datetime index
    #data["Datetime"] = data.apply(lambda row : str(int(row.Year))+"-"+str(int(row.Day))+"-"+str(int(row.Hour)), axis=1)

    #print(data.head())
    #data.set_index("Datetime", inplace=True)

    # Select only the relevant columns
    data_n = data[['Kp_index',
       'R_Sunspot_No', "Dst_index_nT","ap_index_nT", "f10.7_index",
       'AE_index_nT', 'AL_index_nT', 'AU_index_nT', 'pc_index', 'Lyman_alpha',
       'Proton_flux_>1_Mev', 'Proton_flux_>2_Mev', 'Proton_flux_>4_Mev',
       'Proton_flux_>10_Mev', 'Proton_flux_>30_Mev', 'Proton_flux_>60_Mev',
       'Flux_FLAG',"Date"]]
    data_n.set_index("Date", inplace=True)
    data_n = data_n.replace([-999.9, -1], np.nan)  # Replace missing or invalid values with NaN

    print("OMNI data preprocessed successfully.")
    return data_n


# Function to visualize OMNI data
def plot_omni_data(data):
    plt.figure(figsize=(12, 6))

    # Plot F10.7 solar flux
    plt.subplot(2, 1, 1)
    plt.plot(data.index, data["f10.7_index"], label="F10.7 Solar Flux", color="blue")
    plt.title("F10.7 Solar Flux")
    plt.xlabel("Time")
    plt.ylabel("Flux")
    plt.legend()

    # Plot Ap geomagnetic index
    plt.subplot(2, 1, 2)
    plt.plot(data.index, data["AL_index_nT"], label="AL_index_nT", color="red")
    plt.title("Ap Geomagnetic Index")
    plt.xlabel("Time")
    plt.ylabel("Index")
    plt.legend()

    plt.tight_layout()
    plt.show()

# Example Workflow
if __name__ == "__main__":
    # Parameters
    start_year = 2020
    end_year = 2023

    # Download and preprocess OMNI data
    omni_filepath = "/content/OMNI2-112613-012420.csv"
    #download_omni_data(start_year, end_year)

    omni_data = preprocess_omni_data(omni_filepath)

    # Analyze and visualize the data
    print("Basic statistics:")
    print(omni_data.describe())
    #plot_omni_data(omni_data)

# Function to visualize OMNI data
def plot_omni_data_2(data):
    plt.figure(figsize=(12, 6))

    # Plot F10.7 solar flux
    plt.subplot(2, 1, 1)
    plt.plot(data.index, data["ap_index_nT"], label="apflux", color="blue")
    plt.title("ap  Flux")
    plt.xlabel("Time")
    plt.ylabel("Flux")
    plt.legend()

    # Plot Ap geomagnetic index
    plt.subplot(2, 1, 2)
    plt.plot(data.index, data["Kp_index"], label="Kp_index", color="red")
    plt.title("Ap Geomagnetic Index")
    plt.xlabel("Time")
    plt.ylabel("Index")
    plt.legend()

    plt.tight_layout()
    plt.show()

# Example Workflow
"""
if __name__ == "__main__":
    # Parameters
    start_year = 2020
    end_year = 2021

    # Download and preprocess OMNI data
    omni_filepath = "/content/OMNI2-112613-012420.csv"
    #download_omni_data(start_year, end_year)

    omni_data = preprocess_omni_data(omni_filepath)

    # Analyze and visualize the data
    print("Basic statistics:")
    print(omni_data.describe())
    plot_omni_data(omni_data)

 """

# Parameters
start_year = 2020
end_year = 2023

# Download and preprocess OMNI data
#omni_filepath = "/content/OMNI2-112613-012420.csv"
    #download_omni_data(start_year, end_year)

#omni_data = preprocess_omni_data(omni_filepath)

    # Analyze and visualize the data
print("Basic statistics:")
print(omni_data.describe())

omni_data.index

df=omni_data.copy()
df.index = pd.to_datetime(df.index)

start_date = "2020-01-01"
end_date = "2020-01-24"
filtered_data = df.loc[start_date:end_date]
print(filtered_data)
dates=list(filtered_data.index)

!pip install pymsis

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

import pymsis


lons = range(-180, 185, 5)
lats = range(-90, 95, 5)

#print(dt.datetime.strptime(omni_data.da, "date%Y-%m-%d"))

# One years worth of data at the 12th hour every day
date = np.datetime64("2003-01-01T12:00")

f107=filtered_data["f10.7_index"]
ap=filtered_data["ap_index_nT"]
#output2 = pymsis.calculate(date, lons, lats, alt, f107, f107a, aps)
#output0 = pymsis.calculate(date, lons, lats, alt, f107, f107a, aps, version=0)
#diff = (output2 - output0) / output0 * 100



# Example locations (latitude, longitude, altitude in km)
latitudes = np.array([30.0, 40.0])
longitudes = np.array([-75.0, -80.0])
altitudes = np.array([400, 500])


atmospheric_data = pymsis.calculate(dates, altitudes, latitudes, longitudes, f107, ap)
densities = atmospheric_data[:, 0, 0, 0, 5]
print("Simulated densities (kg/m^3):", densities)# Extract density (kg/m^3) from the output


"""

#  diff is now of the shape (1, nlons, nlats, 1, 11)
# Get rid of the single dimensions
diff = np.squeeze(diff)

fig, axarr = plt.subplots(nrows=3, ncols=3, constrained_layout=True, figsize=(8, 6))
xx, yy = np.meshgrid(lons, lats)
norm = mpl.colors.Normalize(-50, 50)
cmap = mpl.colormaps["RdBu_r"]
for i, variable in enumerate(pymsis.Variable):
    if i > 8:
        break
    ax = axarr.flatten()[i]
    mesh = ax.pcolormesh(
        xx, yy, diff[:, :, variable].T, shading="auto", norm=norm, cmap=cmap
    )
    ax.set_title(f"{variable.name}")

plt.colorbar(
    mesh, ax=axarr, label="Change from MSIS-00 to MSIS2 (%)", orientation="horizontal"
)

plt.show()

"""

!pip install pyamps

from pyamps import AMPS
m = AMPS(350, # Solar wind velocity in km/s
              -4, # IMF By (GSM) in nT
              -3, # IMF Bz (GSM) in nT,
              20, # dipole tilt angle in degrees
              80) # F107_index
 # make summary plot:
m.plot_currents()

import numpy as np
mlat, mlt = np.array([75, -75]), np.array([12, 12])
Ju = m.get_upward_current(mlat, mlt)

data = pd.read_csv("/content/SWARMA_POD_RD_01282014-01272020.csv", skiprows=0)

print(data.head())

df.head()

f107 = filtered_data["f10.7_index"].dropna()
ap = filtered_data["ap_index_nT"].dropna()

# Find common non-NaN dates
common_dates = f107.index.intersection(ap.index)
f107 = f107.loc[common_dates]
ap = ap.loc[common_dates]

dates = list(common_dates)

dates

import pandas as pd
import numpy as np
import pymsis

# Prepare and filter data
df = omni_data.copy()
df.index = pd.to_datetime(df.index)

start_date = "2020-01-01"
end_date = "2020-01-24"
filtered_data = df.loc[start_date:end_date]

# Aggregate data to match dates
f107 = filtered_data["f10.7_index"].groupby(filtered_data.index.date).mean()
f107a = f107.rolling(window=81, min_periods=1).mean()
ap_daily = filtered_data["ap_index_nT"].groupby(filtered_data.index.date).mean()

print("F10.7 shape:", f107.isna().values.sum())
print("F10.7A shape:", f107a.isna().values.any())



# Align indices
aligned_dates = pd.to_datetime(f107.index)
f107 = np.array(f107)
f107a = np.array(f107a)

# Create aps array (broadcast daily ap values to 7 slots per day)
aps = np.array([np.repeat(ap_value, 7) for ap_value in ap_daily])

# Example locations (latitude, longitude, altitude in km)
latitudes = np.array([30.0, 40.0])
longitudes = np.array([-75.0, -80.0])
altitudes = np.array([400, 500])

f107 = np.nan_to_num(f107, nan=150.0)  # Replace NaN with 150 (a typical mid-range value)
f107a = np.nan_to_num(f107a, nan=150.0)
aps = np.nan_to_num(aps, nan=15.0)  # Replace NaN in aps with a typical geomagnetic value





# Simulate atmospheric data
try:
    atmospheric_data = pymsis.calculate(aligned_dates, altitudes, latitudes, longitudes, f107, f107a, aps)
    densities = atmospheric_data[:, 0, 0, 0, 5]  # Extract density (kg/m^3)
    print("Simulated densities (kg/m^3):", densities)
except Exception as e:
    print("Error in pymsis calculation:", e)


print("Dates shape:", len(aligned_dates))
print("F10.7 shape:", f107.shape)
print("F10.7A shape:", f107a.shape)
print("Ap shape:", aps.shape)

print("F10.7 values:", f107)
print("F10.7A values:", f107a)
print("Ap indices:", aps)
print("Dates:", aligned_dates)
print("Latitudes:", latitudes)
print("Longitudes:", longitudes)
print("Altitudes:", altitudes)

!pip show pymsis
!pip install --force-reinstall pymsis

import pymsis
import numpy as np
import pandas as pd

# Example test data
test_dates = pd.date_range(start="2020-01-01", periods=3, freq="D")  # 3 test dates
test_f107 = np.array([150.0, 160.0, 170.0])                         # Example F10.7 indices
test_f107a = np.array([140.0, 150.0, 160.0])                        # Example F10.7A indices
test_aps = np.array([
    [10, 15, 20, 25, 30, 35, 40],  # Ap values for day 1
    [12, 16, 22, 28, 34, 38, 42],  # Ap values for day 2
    [14, 18, 24, 30, 36, 40, 44]   # Ap values for day 3
])

# Locations: latitudes, longitudes, altitudes
latitudes = np.array([30.0])
longitudes = np.array([-75.0])
altitudes = np.array([400.0])  # Altitude in km

# Calculate atmospheric data
try:
    atmospheric_data = pymsis.calculate(test_dates, altitudes, latitudes, longitudes, test_f107, test_f107a, test_aps)
    densities = atmospheric_data[:, 0, 0, 0, 5]  # Extract density (kg/m^3)
    print("Test densities (kg/m^3):", densities)
except Exception as e:
    print("Pymsis calculation error:", e)

df = pd.read_csv("/content/SWARMA_POD_RD_01282014-01272020.csv", skiprows=0)

df.head()

